- .github/workflows/delete_old_workflows.yaml
Add [delete old workflows GitHub actions workflow cron job](https://github.com/marketplace/actions/delete-workflow-runs).
> .github/workflows: add delete old workflows GitHub actions workflow

- src/components/TheFooter.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Into the TheFooter component.
**Screenshots**
> src/components: add deployed frontend app version info

- src/components/__tests__/CardEvent.cy.js
To fix run test during upgrade JS lib:
@typescript-eslint/eslint-plugin ^5.10.0 -> ^6.0.0 
@typescript-eslint/parser ^5.10.0 -> ^6.0.0
Error message:
```
Running:  CardEvent.cy.js                                                                (6 of 33)
App •  LINT  • Error:
8:17:11 AM [vite] Internal server error: 
/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/src/components/__tests__/CardEvent.cy.js
18:7  error  'icons' is assigned a value but never used  @typescript-eslint/no-unused-vars
✖ 1 problem (1 error, 0 warnings)
Plugin: quasar:eslint
File: /home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/src/components/__tests__/CardEvent.cy.js
at formatError (/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-fronten …
```
> src/components/__tests__: comment unused const var

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/LoginPage.vue
- test/cypress/e2e/login.spec.cy.js
* Update login page colors based on Figma design
* Add page title
* Add title tests
> src/pages: add login page title

- src/components/BannerRoutes.vue
- src/components/__tests__/BannerRoutes.cy.js
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/IndexPage.vue
* Add variant "start" to `BannerRoutes`. This will be used to display various screens at different times of the challenge
* Update button styling
* Add new translation strings
* Simplify plural handling in translations
* Update tests
* Apply default variant in `IndexPage`.
> src/components: add BannerRoutes component variant property

- .github/workflows/run_tests.yaml
- README.md
Upgrade Node.js version to the last LTS Iron 20.x version.
> Upgrade Node.js version to the last LTS Iron 20.x version

- .husky/pre-commit
- .lintstagedrc
- doc/dev/pre_commit.md
- package.json
- yarn.lock
Install and use pre-commit hook JS lib husky, lint-staged.
Doc ./doc/dev/pre_commit.md
> Install and use pre-commit hook JS lib husky, lint-staged

- .github/workflows/build_dev_dockefile_docker_image.yaml
With image name ride-to-work-by-bike-frontend-dev.
> .github/workflows: automatically build and push dev Dockerfile Docker image

- package.json
- yarn.lock
Move cypress-image-snapshot JS lib into dev dependencies section.
> Move cypress-image-snapshot JS lib into dev dependencies section

- docker/Dockerfile
Fix installing only app dependencies in production Docker image.
> docker: fix installing only app dependencies in production Docker image

- src/components/CountdownChallenge.vue
- src/components/CountdownEvent.vue
- src/components/__tests__/CountdownEvent.js
- src/mocks/homepage.ts
- src/pages/IndexPage.vue
- test/cypress/e2e/home.spec.cy.js
- test/cypress/e2e/login.spec.cy.js
* Rename `EventCountdown` to `CountdownEvent`
* Refactor countdown logic by using `useCountdown` composable
* Fix lint errors
> src/components: rename EventCountdown component to CountdownEvent

- index.html
- src/components/BannerApp.vue
- src/components/BannerImage.vue
- src/components/BannerRoutes.vue
- src/components/CardChallenge.vue
- src/components/CardEvent.vue
- src/components/CardFollow.vue
- src/components/CardOffer.vue
- src/components/CardPost.vue
- src/components/CardProgress.vue
- src/components/CardProgressSlider.vue
- src/components/CardStats.vue
- src/components/FooterBar.vue
- src/components/HelpButton.vue
- src/components/LanguageSwitcher.vue
- src/components/RideToWorkByBike.vue
- src/components/SectionColumnsTest.vue
- src/components/__tests__/ContactForm.cy.js
- src/components/__tests__/DrawerMenu.cy.js
- src/components/types/Card.ts
- src/layouts/MainLayout.vue
- src/utils/get_app_conf.js
- test/cypress/support/commands.js
- test/cypress/support/component-index.html
Format repo with `yarn format`.
> Format repo with yarn format

- src/components/__tests__/BadgeAchievement.cy.js
- src/components/__tests__/BannerApp.cy.js
- src/components/__tests__/BannerImage.cy.js
- src/components/__tests__/BannerRoutes.cy.js
- src/components/__tests__/CardChallenge.cy.js
- src/components/__tests__/CardEvent.cy.js
- src/components/__tests__/CardFollow.cy.js
- src/components/__tests__/CardOffer.cy.js
- src/components/__tests__/CardPost.cy.js
- src/components/__tests__/CardProgress.cy.js
- src/components/__tests__/CardProgressSlider.cy.js
- src/components/__tests__/CardStats.cy.js
- src/components/__tests__/ContactForm.cy.js
- src/components/__tests__/CountdownChallenge.cy.js
- src/components/__tests__/DrawerHeader.cy.js
- src/components/__tests__/FooterBar.cy.js
- src/components/__tests__/FormLogin.cy.js
- src/components/__tests__/HelpButton.cy.js
- src/components/__tests__/LanguageSwitcher.cy.js
- src/components/__tests__/ListCardFollow.cy.js
- src/components/__tests__/ListCardOffer.cy.js
- src/components/__tests__/ListCardPost.cy.js
- src/components/__tests__/ListCardProgress.cy.js
- src/components/__tests__/MenuLinks.cy.js
- src/components/__tests__/NewsletterFeature.cy.js
- src/components/__tests__/NewsletterItem.cy.js
- src/components/__tests__/SliderProgress.cy.js
* Replace `#fff` and `#000` with `black` and `white` variables from global config.
> src/components/__tests__: replace hex black and white with global config variables

- src/components/FormLogin.vue
- src/components/LoginButtons.vue
- src/components/__tests__/LoginButtons.cy.js
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
* Add `LoginButtons.vue` component for 3rd party authentication
* Add `LoginButtons.cy.js` tests
* Incorporate buttons to the `login` state of `FormLogin` component
> src/components: add LoginButtons component

- ride_to_work_by_bike_config.toml
- src/boot/global_vars.ts
- src/components/FooterBar.vue
- src/components/__tests__/FooterBar.cy.js
- src/components/types/Config.ts
- src/utils/get_app_conf.js
* Rename global config variables (external urls)
* Update tests for `FooterBar` social menu links
* Test external links with `cy.request` command
> src/components: extend FooterBar component tests

- src/components/__tests__/FooterBar.cy.js
Fixes issue #126 
* Add custom user-agent settings to `cy.request` based on local browser settings.
> src/components/__tests__: fix FooterBar.cy.js test provides valid URLs for social links under macOS with Google Chrome

- src/components/FormLogin.vue
- src/components/FormRegister.vue
- src/components/__tests__/FormRegister.cy.js
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/router/routes.ts
- test/cypress/support/component.js
* Add link to register as coordinator
* Add link to login
* Add tests
> src/components: add links to coordinator registration and login

- src/components/LoginRegisterHeader.vue
- src/components/__tests__/LoginRegisterHeader.cy.js
- src/pages/LoginPage.vue
- src/pages/RegisterPage.vue
- test/cypress/e2e/login.spec.cy.js
Refactor header into a standalone component to be used in `LoginPage` `RegisterPage` `RegisterChallengePage` and possibly others.
* Migrate some of the tests into the component test suite.
* Update page documentation
> src/components: refactor header used on login and register pages to a standalone component

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/RegisterCoordinatorPage.vue
- src/router/routes.ts
- test/cypress/e2e/register_challenge.spec.cy.js
- test/cypress/e2e/register_coordinator.spec.cy.js
- test/cypress/support/commonTests.js
Add `RegisterCoordinatorPage` with title + information card.
> src/pages: add RegisterCoordinatorPage component page

- src/components/__tests__/FormLogin.cy.js
- src/components/__tests__/FormRegister.cy.js
- src/components/global/FormFieldEmail.vue
- src/components/login/FormLogin.vue
- src/components/register/FormRegister.vue
Use email field component in form components:
* `FormLogin`
* `FormRegister`
Remove redundant tests (email validation).
> src/component: use email field component in form componets

- test/cypress/e2e/home.spec.cy.js
> test/cypress/e2e: if 'allows user to scroll to top using the footer button' test fail skip it

- src/pages/RegisterChallengePage.vue
- test/cypress/e2e/register_challenge.spec.cy.js
> src/pages: fix deployed RegisterChallengePage stepper component img URL

- src/components/register/FormRegisterCoordinator.vue
Fixes issue #211 
Replaced incorrect `v-model` variable name.
> components/register: fix variable name

- src/components/__tests__/ContactForm.cy.js
- src/components/__tests__/HelpButton.cy.js
- src/components/__tests__/LoginRegisterHeader.cy.js
- src/components/global/ContactForm.vue
- test/cypress/e2e/home.spec.cy.js
- test/cypress/e2e/login.spec.cy.js
Use `FormFieldTextRequired` in `ContactForm` (subject field)
* Replace input with component
* Update test selectors to match new component
> components/global: use `FormFieldTextRequired` component in `ContactForm` component

- src/components/global/HelpButton.vue
Fixes issue #234 
* Add a single common wrapper div in `HelpButton.vue` component
> components/global: add root wrapper div to pass attributes to

- src/components/__tests__/FormFieldOptionGroup.cy.js
- src/components/form/FormFieldOptionGroup.vue
- src/components/global/FormFieldTestWrapper.vue
- src/components/types/Form.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Add new component to show selectable options on `RegisterChallengePage`.
Component is not being used yet. It will become part of the second form step.
Preview in test.
> coponents/form: add `FormFieldOptionGroup` component

- src/components/form/FormFieldOptionGroup.vue
- src/composables/useStepperValidation.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/RegisterChallengePage.vue
- test/cypress/e2e/register_challenge.spec.cy.js
Use `FormFieldOptionGroup` to select the type of participants in a team (`RegisterChallengePage`).
* Update step validation for laters steps of the form
* Add new translation strings
* Update tests
> src/pages: add `FormFieldOptionGroup` to form step Participation

- src/components/__tests__/FormFieldCompanySelect.cy.js
- src/components/form/FormFieldCompanySelect.vue
- src/components/global/FormFieldTestWrapper.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/RegisterChallengePage.vue
Add `FormFieldCompanySelect` and use it in `RegisterChallengePage`
Offers search functionality over an `QOptionGroup` component.
* Add tests
To do in next PR: Add dialog for registering a new company.
> components/form: add company select widget for 4th step registration challenge

- src/components/__tests__/FormFieldListMerch.cy.js
- src/components/__tests__/FormFieldPhone.cy.js
- src/components/form/FormCardMerch.vue
- src/components/form/FormFieldListMerch.vue
- src/components/form/FormFieldRadioRequired.vue
- src/components/global/FormFieldPhone.vue
- src/components/global/FormFieldTestWrapper.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/fixtures/listMerch.json
Add `DialogDefault` with merch options (gender, size, package tracking, ...) to `FormFieldListMerch`.
* The gender settings inside dialog corresponds with currently opened tab
* Upon select, the card button is highlighted
* If package tracking is selected, phone number is required
> components/form: add dialog for merch options

- src/components/__tests__/FormFieldListMerch.cy.js
- src/components/__tests__/SliderMerch.cy.js
- src/components/form/FormFieldListMerch.vue
- src/components/form/SliderMerch.vue
- src/components/types/Form.ts
- src/components/types/index.ts
- test/cypress/fixtures/sliderMerch.json
Add component `SliderMerch` to be used in `FormFieldListMerch` to show merch images.
Uses swiper component styled with `::part()` selector.
* Add tests
* Add fixture for image array
> components/form: add component `SliderMerch` for displaying images in merch dialog

- src/components/form/FormFieldListMerch.vue
Register challenge step 7: Merch List
Add scroll to tab list when deselecting "I don't want a shirt or a neck warmer" checkbox.
> components/form: scroll to tab list when is shown

- ride_to_work_by_bike_config.toml
- src/components/__tests__/CardChallenge.cy.js
- src/components/__tests__/CardEvent.cy.js
- src/components/__tests__/CardFollow.cy.js
- src/components/__tests__/CardOffer.cy.js
- src/components/__tests__/CardPost.cy.js
- src/components/__tests__/CardStats.cy.js
- src/components/__tests__/CountdownEvent.cy.js
- src/components/homepage/CountdownEvent.vue
- src/components/types/Config.ts
- src/utils/get_app_conf.js
To update `CountdownEvent` component based on the figma design:
Fix missing `.cy` prefix in component test file.
Update tests:
* Update font-sizes and color
* Update background color and border-radius
* Add matching global config
Update component to pass tests.
> components/homepage: update CountdownEvent styles based on graphic design

- ride_to_work_by_bike_config.toml
- src/components/__tests__/BannerImage.cy.js
- src/components/homepage/BannerImage.vue
- src/components/types/Banner.ts
- src/components/types/Config.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/mocks/homepage.ts
- src/utils/get_app_conf.js
- test/cypress/fixtures/bannerImage.json
To update `BannerImage` component based on the figma design:
Edit tests:
* Update font-sizes and color
* Add max width to the banner (config)
* Update background color, border, and border-radius
* Add button element
* Add data fixture
Edit component to pass tests.
Changes also include updates to text section padding and image aspect ratio.
> components/homepage: update BannerImage styles based on graphic design  

- src/components/__tests__/CardEvent.cy.js
- src/components/homepage/CardEvent.vue
Local UI tests fail on testing the width of a dialog column - they required 100% width value to pass.
CLI tests required 95% width value to pass.
To fix this:
* Introduce `.row` wrapper in the component ensure control over parent styles.
* Test for 100% width.
> components/homepage: update CardEvent layout + test

- src/components/__tests__/CardEvent.cy.js
- src/components/global/ButtonAddToCalendar.vue
- src/components/homepage/CardEvent.vue
- src/components/types/Card.ts
- src/components/types/Item.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/mocks/homepage.ts
- test/cypress/fixtures/cardEvent.json
* Refactor add-to-calenar button in `CardEvent` into `ButtonAddToCalendar` component.
* Add dropdown with different calendar types.
* Extend tests for `CardEvent`
* Refactor data in card event tests to use fixuture
> components/global: refactor button add-to-calendar and add dropdown menu

- ride_to_work_by_bike_config.toml
- src/components/__tests__/RouteLockedContent.cy.js
- src/components/routes/RouteLockedContent.vue
- src/components/types/Config.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/utils/get_app_conf.js
Adds component `RouteLockedContent` to show informational video on the `/routes` path when challenge is not on.
* Add video url to config
* Add translation string
* Add test
> src/components/routes: add RouteLockedContent component 

- src/components/__tests__/ListCardPost.cy.js
Simplify tests by removing `cy.window().then(() => {` function.
Refactor tests into `coreTests` function.
> src/components/__tests__: simplify ListCardPost tests by removing cy.window wrapper

- src/components/__tests__/CardProgress.cy.js
- src/components/__tests__/ResultsList.cy.js
- src/components/homepage/CardProgress.vue
- src/components/results/ResultsList.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Add component `ResultsList` to render user's result statistics.
* Refactor share button label to be used across app (global context - shared with `CardProgress`)
* Add tests
> src/components/results: add ResultsList component to be used in results detail view

- src/components/results/ResultsList.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Update value units in `ResultsList` component according to typographic rules.
Unit is on the same line as value.
Description is below.
> src/components/results: update unit position according to typographic rules

- src/components/__tests__/BannerChallengeDescription.cy.js
- src/components/results/BannerChallengeDescription.vue
- src/components/types/Challenge.ts
- src/composables/useRoutes.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/fixtures/bannerChallengeDescription.json
Add `BannerChallengeDescription` component.
* Add component for displaying challenge details.
* Add type ChallengeDescription for data.
* Add string translation
* Add tests
> src/components/results: add component BannerChallengeDescription to display challenge details

- src/components/__tests__/ListCardSlider.cy.js
- src/components/global/ListCardSlider.vue
- src/components/types/Card.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/ResultsDetailPage.vue
- test/cypress/fixtures/listResultsPrizes.json
Add `ListCardSlider` based on `ListCardPost` component to be reused with different card types if needed.
* Add fixture for displaying and testing a particular use case
* Display component on `ResultsDetailPage`
> src/components/global: add component ListCardSlider to render slider sections

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/mocks/layout.ts
- src/pages/CommunityPage.vue
- src/router/routes.ts
- src/router/routes_conf.ts
- test/cypress/e2e/community.spec.cy.js
- test/cypress/fixtures/listCardsEvent.json
Adds CommunityPage at route `/community`.
* Display heading + select input for selecting city.
* Display current local events with data from fixture.
* Add basic tests.
> src/pages: add new CommunityPage component for displaying community news

- src/components/__tests__/CardFollow.cy.js
- src/components/__tests__/ListCardFollow.cy.js
- src/mocks/homepage.ts
- src/pages/CommunityPage.vue
- src/pages/IndexPage.vue
- test/cypress/fixtures/listCardsFollow.json
Use `CardListFollow` component on `CommunityPage`.
* Update `CardListFollow` and `CardFollow` tests using fixture
* Remove dependency on old homepage mocks file (as data is no longer relevant only for HP)
* Update tests using fixture and alias method for passing variable data
* Update tests using `coreTests` function to run common tests in different contexts
> src/pages/CommunityPage: use CardListFollow component and update using fixture

- src/components/__tests__/CardOffer.cy.js
- src/components/homepage/CardOffer.vue
- src/components/types/Card.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/mocks/layout.ts
- src/pages/PrizesPage.vue
- src/router/routes.ts
- src/router/routes_conf.ts
- test/cypress/e2e/prizes.spec.cy.js
- test/cypress/fixtures/listCardsPrizes.json
Add new route `/prizes` and a `PrizesPage` component.
Display a list of special offers:
Update and refactor `CardOffer` component 
* More flexible setup with Metadata Array
* Use v-html to display rich text format in title
* Update `CardOffer` tests
* Add `voucher` display section
* Add new fixture data
> src/pages/PrizesPage: add page to display prizes

- src/components/homepage/BannerApp.vue
- src/components/homepage/CardChallenge.vue
- src/components/homepage/CardEvent.vue
- src/components/homepage/CardFollow.vue
- src/components/homepage/CardOffer.vue
- src/components/homepage/CardPost.vue
- src/components/homepage/CardProgress.vue
- src/components/homepage/CardProgressSlider.vue
- src/components/homepage/CardStats.vue
- src/components/login/BannerAppButtons.vue
- src/components/login/FormLogin.vue
Unify and simplify importing global config file (in older components).
Remove unnecessary type import.
> src/components: update global config import from boot file

- src/components/__tests__/CardPost.cy.js
- src/components/__tests__/ListCardPost.cy.js
- src/components/homepage/CardPost.vue
- src/components/types/Card.ts
- src/mocks/homepage.ts
- src/pages/CommunityPage.vue
- src/pages/IndexPage.vue
- test/cypress/e2e/community.spec.cy.js
- test/cypress/fixtures/listCardsPost.json
Add `ListCardPost` to `CommunityPage`
Update `ListCardPost` component to use fixtures (instead of old mocks).
Update `CardPost` handling of a `data` prop (changed from `date` object to `string` for better compatibility).
Add `CommunityPage` E2E tests.
> src/pages: add ListCardPost to CommunityPage to display recent blog post

- src/pages/CommunityPage.vue
- test/cypress/e2e/community.spec.cy.js
Use previously created components to render forum post list on `community` page.
Add e2e test.
> src/pages: display forum post list on CommunityPage

- src/components/global/CardPrize.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/PrizesPage.vue
- test/cypress/e2e/prizes.spec.cy.js
- test/cypress/fixtures/listResultsPrizes.json
Use components `SectionColumns` and `CardPrize` to display prizes on `prizes` page.
* Add "full-width" class to card - make it fill available height
* Fix types for `listResultsPrizes` fixture
* Add E2E tests
> src/pages: add section with avaiable prizes to PrizesPage

- src/components/__tests__/FormFieldSelectCity.cy.js
- src/components/form/FormFieldSelectCity.vue
- src/components/global/FormFieldTestWrapper.vue
- src/pages/CommunityPage.vue
- src/pages/PrizesPage.vue
- test/cypress/e2e/community.spec.cy.js
- test/cypress/e2e/prizes.spec.cy.js
Refactor city select element used on different pages.
Extract to `FormFieldSelectCity` component.
Add tests.
Use on `CommunityPage` and `PrizesPage`.
(Tests use `FormFieldTestWrapper` component for simulating v-model behaviour).
> src/components/form: add component FormFieldSelectCity to filter by city

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/mocks/layout.ts
- src/pages/CompanyCoordinatorPage.vue
- src/router/routes.ts
- src/router/routes_conf.ts
- test/cypress/e2e/company_coordinator.spec.cy.js
- test/cypress/e2e/coordinator_page.spec.cy.js
Add company coordinator page with initial state "no coordinator".
Coordinator does not exist so we get title, intro text and image.
* Add route config
* Add e2e tests
> src/pages: add the CompanyCoordinatorPage with initial state

- src/components/__tests__/BannerReminder.cy.js
- src/components/global/BannerReminder.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Add `BannerReminder` component with two buttons (dismiss and confirm)
> src/components/global: add component BannerReminder to display notification for coordinator

- .github/workflows/run_tests.yaml
- src/components/__tests__/ListPartners.cy.js
- src/components/global/ListPartners.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/PrizesPage.vue
- test/cypress/e2e/prizes.spec.cy.js
- test/cypress/fixtures/listPartners.json
- yarn.lock
Add component `ListPartners` to display different types of partner logos in a grid.
Use component on the `PrizesPage`.
* Add fixture
* Add tests
> src/components/global: add component ListPartners for displaying partner logos + show on prizes page

- src/components/__tests__/CardOffer.cy.js
- src/components/__tests__/OfferValidation.cy.js
- src/components/homepage/CardOffer.vue
- src/components/offer/OfferValidation.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/support/component.js
Add component `OfferValidation`. It displays note about validating a discount offer.
It is shown in `CardOffer` component inside the dialog.
* Add component tests
> src/components/offer: add component OfferValidation to display information in Offer dialog

- src/components/__tests__/TaskListCoordinator.cy.js
- src/components/coordinator/TaskListCoordinator.vue
- src/components/types/Task.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/fixtures/taskListCoordinator.json
Add `TaskListCoordinator` component that shows the timeline of tasks that coordinator needs to complete.
Allows to show/hide past tasks and displays a month label for first task of a month.
* Add logic for computing labels and past/future items in an inline composable
* Add tests
> src/components/coordinator: add component TaskListCoordinator to display task timeline

- src/components/__tests__/ProfileTabs.cy.js
- src/components/profile/ProfileTabs.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/ProfilePage.vue
- src/router/routes.ts
- src/router/routes_conf.ts
Add Profile page:
* Specify profile routes (with children corresponding to navigation tabs)
* Add `ProfilePage` page layout
* Add `ProfileTabs` component to display tabs on ProfilePage
* Add test for `ProfileTabs`
> src/pages: add ProfilePage + ProfileTabs component for displaying user profile content

- src/components/__tests__/RoutesCalendar.cy.js
Introduce special condition for challengeLoggingWindowDays = 1 in `RoutesCalendar` tests.
Updated tests still confirm given behaviour, but do not fail on testing previous days which are, in this case, disabled.
> src/components/__tests__: fix routes calendar tests for when challengeLoggingWindowDays = 1

- src/components/__tests__/RoutesCalendar.cy.js
Adds test for max number of items in the calendar.
Accounts for logged routes.
> src/components/__tests__: add test for max number of selected items in calendar

- src/components/routes/CalendarItemDisplay.vue
- src/components/routes/RouteListDisplay.vue
- src/components/routes/RouteListEdit.vue
- src/components/routes/RoutesCalendar.vue
- src/components/types/Route.ts
- src/composables/useCalendarRoutes.ts
- src/composables/useRoutes.ts
Unify types `RouteListDay` and `RouteCalendarDay` into a single type `RouteDay`
Replace across the code.
> src/components/types: unify types for RouteDay

- ride_to_work_by_bike_config.toml
- src/components/types/Config.ts
- src/layouts/MainLayout.vue
- src/pages/RegisterChallengePage.vue
- src/pages/RegisterCoordinatorPage.vue
- src/utils/get_app_conf.js
Add max-width to content in the `MainLayout` (based on UX meeting).
Rename variable `containerWidth` to `containerFormWidth` (used for register + login layout).
Update comments in `ride_to_work_by_bike_config.toml` for better readability.
> src/layouts: add max width to main layout + update docs for config

- src/components/__tests__/CardChallenge.cy.js
- src/components/homepage/CardChallenge.vue
- test/cypress/fixtures/cardChallenge.json
Update the `CardChallenge` component based on graphic design.
* Change colors
* Add image overlay
* Use coreTests function for desktop + mobile context
* Refactor tests using fixture and selectors
> src/components/homepage: update CardChallenge styling and refactor tests

- src/components/__tests__/FormPersonalDetails.cy.js
- src/components/form/FormFieldRadioRequired.vue
- src/components/form/FormPersonalDetails.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/e2e/register_challenge.spec.cy.js
In component `FormPersonalDetails` make gender required.
* Use `FormFieldRadioRequired` to render a required gender field.
* Add hint field (based on Figma design file)
> src/components/form: make Gender field in FormPersonalDetails required

- public/icons/card_event/icons.svg
- src/components/__tests__/CardEvent.cy.js
- src/components/global/ButtonAddToCalendar.vue
- src/components/homepage/CardEvent.vue
Update styling for `CardEvent` component:
* Use new icons, update icon color and sizes
* Update text colors
* Update button color
* Add border (q-card component needs to be replaced by div)
* Refactor tests using selectors
* Refactor tests into shared `coreTests` function
> src/components/homepage: update CardEvent styling based on graphic design

- public/icons/lucide.svg
- src/components/__tests__/CardFollow.cy.js
- src/components/__tests__/ListCardFollow.cy.js
- src/components/homepage/CardFollow.vue
- src/components/homepage/ListCardFollow.vue
Update component ListCardFollow based on graphic design:
* Remove top padding and negative margin
* Add arrow icon
* Put avatar, text and icon into one line
* Stack title + cards
> src/components: update component ListCardFollow based on graphic design

- src/components/__tests__/ProfileDetails.cy.js
- src/components/form/FormUpdateGender.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/ProfilePage.vue
- test/cypress/e2e/profile.spec.cy.js
Add the `profile.spec.cy.js` with E2E tests for the Profile page.
* Update profile page selector
* Fix issue with incorrectly matched gender labels
* Update tests for gender labels to check for fixed issue
* Add missing title translation key
* Add test to check for the translation key
* Add E2E test for changing user settings
> test/cypress/e2e: add E2E tests for the Profile page and fix bugs

- src/components/__tests__/FormFieldCompany.cy.js
- src/components/global/FormFieldCompany.vue
Issue with test: It may not check correctly the proper column width distribution on all screen sizes.
Instead, use the "side-by-side" test command, which is more robust.
This will allow to merge the PR #575.
> src/components/__tests__: fix FormFieldCompany component correct layout

- src/components/form/FormPersonalDetails.vue
Adds correct lang attribute `scss` to the style tag.
Fixes issue of not correctly reading the stylesheet as the CSS rules are expected.
> src/components/form: fix build process minification issue with correct lang attribute

- public/icons/drawer_menu/icons.svg
- src/components/__tests__/DrawerMenu.cy.js
- src/components/global/DrawerHeader.vue
- src/components/global/DrawerMenu.vue
- src/css/quasar.variables.scss
- src/layouts/MainLayout.vue
- src/mocks/layout.ts
- test/cypress/e2e/community.spec.cy.js
- test/cypress/e2e/company_coordinator.spec.cy.js
- test/cypress/e2e/home.spec.cy.js
- test/cypress/e2e/prizes.spec.cy.js
- test/cypress/e2e/results.spec.cy.js
- test/cypress/e2e/results_detail.spec.cy.js
- test/cypress/e2e/routes.spec.cy.js
Update component DrawerMenu:
* Make sidebar primary color.
* Update menu styles based on design.
* Update menu structure to avoid duplication (component used twice for top and bottom section of the menu).
* Update tests (add tests for active vs default item).
* Add new icons.
> src/components: update component DrawerMenu styling based on graphic design

- public/icons/user_select/icons.svg
- src/components/__tests__/UserSelect.cy.js
- src/components/global/DrawerHeader.vue
- src/components/global/UserSelect.vue
- src/components/types/Link.ts
- src/components/types/User.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/layouts/MainLayout.vue
- src/mocks/layout.ts
- test/cypress/e2e/community.spec.cy.js
- test/cypress/e2e/company_coordinator.spec.cy.js
- test/cypress/e2e/home.spec.cy.js
- test/cypress/e2e/prizes.spec.cy.js
- test/cypress/e2e/profile.spec.cy.js
- test/cypress/e2e/results.spec.cy.js
- test/cypress/e2e/results_detail.spec.cy.js
- test/cypress/e2e/routes.spec.cy.js
- test/cypress/e2e/routes_calendar.cy.js
- test/cypress/support/commonTests.ts
Update styling for UserSelect component based on design:
* Blue bordered button with avatar + email (custom dropdown icon).
* Blue bordered dropdown with working menu links and `active` class.
* Update tests for the component.
* Update E2E tests by refactoring desktop sidebar and mobile header tests into common functions.
* Remove old mock data.
* Add translation strings.
> src/components/global: update styling for UserSelect component + tests

- public/icons/card_progress/icons.svg
- src/components/__tests__/CardProgress.cy.js
- src/components/__tests__/CardProgressSlider.cy.js
- src/components/homepage/CardProgress.vue
- src/composables/useCircleSize.ts
- src/css/circular-progress.scss
Update styling for the `CardProgress` component:
* Update colors and font sizes
* Add custom icons
* Update internal structure to better match design (sections with separator in between)
* Update and refactor tests
> src/components/homepage: update styling for the CardProgress component

- public/icons/newsletter_item/icons.svg
- ride_to_work_by_bike_config.toml
- src/components/__tests__/NewsletterItem.cy.js
- src/components/homepage/NewsletterFeature.vue
- src/components/homepage/NewsletterItem.vue
- src/components/types/Config.ts
- src/mocks/homepage.ts
- src/utils/get_app_conf.js
- test/cypress/support/commonTests.ts
Update styling for NewsletterItem component based on design
* Change colors
* Add custom icons
* Emit `follow` event to handle subscription in FE UI
* Add disabled state to buttons
* Update tests
> src/components: update styling for NewsletterItem component

- src/components/__tests__/ProfileTabs.cy.js
- src/components/profile/ProfileTabs.vue
Adds component NewsletterFeature to the ProfileTabs newsletter section.
This component is reused from Homepage.
Adds test for component visibility in the newsletter tab.
> src/components/profile: add component NewsletterFeature to the ProfileTabs section

- src/components/__tests__/ListCardFollow.cy.js
- src/components/__tests__/ListCardOffer.cy.js
- src/components/__tests__/ListCardPost.cy.js
- src/components/__tests__/ListCardProgress.cy.js
- src/components/__tests__/ProfileDetails.cy.js
- src/components/__tests__/RoutesApps.cy.js
- src/components/__tests__/RoutesBottomPanel.cy.js
- src/components/__tests__/SectionHeading.cy.js
- src/components/__tests__/SliderProgress.cy.js
- src/components/global/SectionHeading.vue
- src/components/profile/ProfileDetails.vue
Update styling for `SectionHeading` component (font size, weight and color).
* Use the `SectionHeading` component in `ProfileDetails` for titles to unify the styles.
* Remove unncessary tests from `ProfileDetails` component test suite.
* Remove duplicate styling tests from various components using `SectionHeading`.
> src/components/global: update styling for SectionHeading component

- src/components/__tests__/BadgeAchievement.cy.js
- src/components/homepage/BadgeAchievement.vue
Update `BadgeAchievement` styling:
* Changed component colors
* Tweaked whitespace sizing.
* Refactored tests into a share `coreTests` function.
* Add tests for border radius, share button and text colors.
> src/components: update BadgeAchievement styling + test suite

- src/components/__tests__/UserSelect.cy.js
- src/components/global/UserSelect.vue
- src/components/types/User.ts
- src/composables/useApi.ts
- src/mocks/layout.ts
- src/router/index.ts
- src/stores/login.ts
- test/cypress/e2e/register.spec.cy.js
- test/cypress/fixtures/loggedUser.json
- test/cypress/support/commonTests.ts
Update `UserSelect` with data from login store:
* Display user email in the dropdown button.
* Display user full name as the alt of the dropdown avatar.
* Display user placeholder if user does not have an image.
* Update component test to draw data from fixture.
* Add E2E test that performs login and checks the displayed email value.
> src/components: update UserSelect component to display logged user data

- src/components/register/EmailVerification.vue
> src/components/register: fix hidding email verification page after user login

- src/stores/register.ts
Prevent token concatenate deduplication.
> src/stores: fix request authorization header concatenate token string

- ride_to_work_by_bike_config.toml
- src/components/register/EmailVerification.vue
- src/components/types/Config.ts
- src/utils/get_app_conf.js
Add `checkIsEmailVerifiedInterval` global app variable.
> Add checkIsEmailVerifiedInterval global app variable

- ride_to_work_by_bike_config.toml
- src/components/__tests__/DrawerHeader.cy.js
- src/components/__tests__/HeaderLogo.cy.js
- src/components/__tests__/LoginRegisterHeader.cy.js
- src/components/global/DrawerHeader.vue
- src/components/global/HeaderLogo.vue
- src/components/global/LoginRegisterHeader.vue
- src/components/types/Config.ts
- src/utils/get_app_conf.js
Refactor app logo into a separate`HeaderLogo` component:
* Add `HeaderLogo` component with link to home page.
* Use component in `DrawerHeader` component.
> src/components: refactor app logo into a separate HeaderLogo component

- src/components/__tests__/EmailVerification.cy.js
- src/components/register/EmailVerification.vue
During `EmailVerification` component mount as fixture props.
Fixes error message:
```
2) makes an email verification request
3 passing (11s)
2 failing
1) <EmailVerification>
desktop
makes an email verification request:
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed
out waiting `5000ms` for the 1st request to the route:
`emailVerificationRequest`. No request ever occurred.
```
> src/components/__tests__: fix load Cypress tests fixture JSON file

- src/components/__tests__/CoordinatorTabs.cy.js
- src/components/coordinator/CoordinatorTabs.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/router/routes.ts
- src/router/routes_conf.ts
Add `CoordinatorTabs` component for coordinator page.
* Specify routes for coordinator subpages
* Add tabs component
* Test tabs component
> src/components: add CoordinatorTabs component for coordinator page

- src/components/__tests__/MenuLinks.cy.js
Check attribute URL in `MenuLinks` component against the global config via useSocialLinks composable.
Use loop to test each of the links' title and href.
Cleanup and add comments.
> src/components/__tests__: test href attributes from config in MenuLinks

- ride_to_work_by_bike_config.toml
- src/components/types/Config.ts
- src/utils/get_app_conf.js
Add endpoint `rest/challenge/registration/user/` to global config.
> Config: add endpoint urlApiChallengeRegistrationUser

- src/components/types/Form.ts
- src/stores/registerChallenge.ts
Update `registerChallenge` store property gender type to enum `Gender`.
> src/stores: update registerChallenge store gender type to enum

- src/stores/registerChallenge.ts
Add `NewsletterType` type for `registerChallenge` store newsletter prop.
> src/stores: add NewsletterType type for registerChallenge newsletter prop

- src/components/__tests__/MenuLinks.cy.js
- src/components/global/MenuLinks.vue
- src/composables/useSocialLinks.ts
Translate titles in `useSocialLinks` and display them in `MenuLinks` component.
The same `title` attribute is displayed in `SocialBar` component.
> src/components: translate titles in useSocialLinks and display them in MenuLinks component

- public/icons/login_register_header/icons.svg
- src/components/__tests__/LoginRegisterHeader.cy.js
- src/components/global/LoginRegisterHeader.vue
- test/cypress/e2e/register.spec.cy.js
Add logout button to `LoginRegisterHeader` desktop view.
* Shown when user is logged in.
* Styles tested in component tests.
* User flow tested in E2E `register` tests.
> src/components: add logout button to LoginRegisterHeader desktop view

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/CompanyCoordinatorPage.vue
- src/router/routes.ts
- test/cypress/e2e/community.spec.cy.js
- test/cypress/e2e/company_coordinator.spec.cy.js
Add `CoorinatorTabs` component to the `CompanyCoordinatorPage`.
Add redirect from the base URL to the first tab URL.
Add E2E tests for the tab navigation.
> src/pages: add CoorinatorTabs to the CompanyCoordinatorPage

- src/components/__tests__/FormFieldCompanyAddress.cy.js
- src/components/types/Form.ts
- src/components/types/Organization.ts
- src/composables/useSelectedOrganization.ts
- src/stores/registerChallenge.ts
- test/cypress/fixtures/formOrganizationOptions.json
Update data properties in `registerChallenge` store + their getters and setters.
Set organization, subsidiary, team and member `id`s to `number` type and update fixture.
> src/stores: update data structure in registerChallenge store + update Organization types

- src/components/coordinator/CoordinatorTabs.vue
- test/cypress/e2e/company_coordinator.spec.cy.js
Add component `TaskListCoordinator` to `CoordinatorTabs`.
Add E2E tests for this tab:
- test ability to show past tasks
- add timestamp to have past and future tasks based on fixture data
- wrap other tests with different contexts so we do not have to handle updates to UI with `clock.tick()` function.
> src/components: add component TaskListCoordinator to CoordinatorTabs

- src/i18n/index.js
Fix error message (web browse dev console):
```
Uncaught (in promise) TypeError: error loading dynamically imported
module: https://rtwbb-test.dopracenakole.net/assets/cs.toml
```
> src/i18n: fix i18n locales TOML files dynamic import in builded app

- src/components/__tests__/MenuLinks.cy.js
Add tests for link URLs in `MenuLinks` component.
> src/components/__tests__: add tests for link URLs in MenuLinks component

- src/components/__tests__/FormRegister.cy.js
- src/components/register/FormRegister.vue
Remove newsletter checkbox in FormRegistration component, since it has no function.
Update component test.
> src/components: remove newsletter checkbox in FormRegistration component

- src/components/__tests__/FormFieldCompany.cy.js
- src/components/__tests__/FormRegisterCoordinator.cy.js
- src/components/global/FormFieldCompany.vue
- src/components/types/Form.ts
- src/components/types/Organization.ts
- src/composables/useApi.ts
- src/stores/register.ts
- src/utils/index.ts
- test/cypress/e2e/register_coordinator.spec.cy.js
- test/cypress/fixtures/formFieldCompany.json
- test/cypress/fixtures/formFieldCompanyCreateRequest.json
- test/cypress/fixtures/formFieldCompanyNext.json
- test/cypress/support/commonTests.ts
- test/cypress/utils/index.ts
Fix waiting for organizations select widget loading all options.
> src/components: fix FormFieldCompany component data fetching

- src/components/form/FormFieldOptionGroup.vue
- src/pages/RegisterChallengePage.vue
Update the value of `organizationType` in `RegisterChallengePage` from `registerChallenge` store.
Fix `v-model` prop type for `FormFieldOptionGroup` component.
> src/pages: update organizationType in RegisterChallengePage from registerChallenge store

- src/components/form/FormFieldOptionGroup.vue
- src/pages/RegisterChallengePage.vue
- src/stores/registerChallenge.ts
Add `null` as valid `setOrganizationType` param type in registerChallenge store.
> src/stores: remove null from organizationType param type in registerChallenge store

- src/components/__tests__/FormSelectOrganization.cy.js
- src/components/form/FormSelectOrganization.vue
In `FormSelectOrganization` component pass `organizationType` from store to `FormFieldSelectTable` component.
Test the prop value by modifying the `data-cy` selector and comparing to store value.
> src/components/form: pass organizationType from store to FormFieldSelectTable component

- src/components/global/FormFieldCompany.vue
- src/composables/useApiGetOrganizations.ts
Refactor "load companies" behaviour into the `useApiGetOrganizations` composable.
This will reduce the size of `FormFieldCompany` component and allow for code reuse.
> src/composables: refactor load companies behaviour into the useApiGetOrganizations composable

- test/cypress/fixtures/formOrganizationOptions.json
Update custom fixture `formOrganizationOptions`.
Change `cityChallenge` type to number to fix TS error (in `FormSelectOrganization` component).
> test/cypress/fixtures: fix formOrganizationOptions fixture cityChallenge number type

- src/components/__tests__/FormSelectTeam.cy.js
- src/components/form/FormFieldSelectTable.vue
- src/components/form/FormSelectTeam.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- src/pages/RegisterChallengePage.vue
Refactor register challenge Team step into a separate component `FormSelectTeam`.
This component will handle API calls and UI changes.
> src/components: refactor register challenge team step into FormSelectTeam component

- src/components/__tests__/FormAddCompany.cy.js
- src/components/form/FormAddCompany.vue
In `FormAddCompany` component, hide/show message `form-add-company-permission` if `organizationType` is `company`.
Update `FormAddCompany` component tests to check for message visibility.
> src/components: hide/show message based on organizationType in FormAddCompany

- src/components/__tests__/FormFieldListMerch.cy.js
- src/components/__tests__/ProfileDetails.cy.js
- src/components/form/FormFieldListMerch.vue
- src/components/form/FormPersonalDetails.vue
Replace gender strings with enums in `FormFieldListMerch`.
Fix missing `QCard` type.
> src/components: replace gender strings with enums in FormFieldListMerch

- src/components/__tests__/FormFieldListMerch.cy.js
- src/components/form/FormFieldListMerch.vue
- test/cypress/e2e/register_challenge.spec.cy.js
Update FormFieldListMerch based on graphic design UI changes:
* Duplicate input for size so that it is always visible.
* Move phone number input + checkboxes from dialog to card.
* Update tests to reflect the changes.
> src/components: update FormFieldListMerch based on graphic design

- src/components/__tests__/RegisterChallengePayment.cy.js
- src/components/form/FormFieldDonation.vue
- src/components/register/RegisterChallengePayment.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/support/commands.js
* Add payment total display in `RegisterChallengePayment`.
* Calculate total price based on `paymentSubject`, `amount` and `donation`.
* Update `FormFieldDonation` component to emit donation value to parent component.
* Add component tests for different situations where total price is (not) displayed.
* Add custom command for testing total price with donation amount (as it was repeated several times in test).
> src/components: add payment total display in RegisterChallengePayment

- src/components/__tests__/FormRegister.cy.js
- src/components/types/Challenge.ts
- src/stores/challenge.ts
- test/cypress/fixtures/apiGetThisCampaign.json
Add `daysActive` and `maxTeamMembers` loaded from `this_campaign` endpoint to the `challenge` store.
* Update test fixture.
* Add component test checking the value in store after API is loaded.
> src/stores: add daysActive and maxTeamMembers to the challenge store

- src/components/__tests__/FormFieldCompany.cy.js
- src/components/global/FormFieldCompany.vue
- test/cypress/e2e/register_challenge.spec.cy.js
Fix displaying select value after reload in `FormFieldCompany` component.
Use option object as `v-model` value and update option after mounting and loading options.
> src/components/global: fix displaying select value after reload in FormFieldCompany component

- src/pages/RegisterChallengePage.vue
- src/stores/registerChallenge.ts
- test/cypress/e2e/register_challenge.spec.cy.js
Show button loader (and disable back button) when updating registration via API in `RegisterChallengePage`.
* Add computed "loading" variable from store.
* Use `loading` and `disable` props.
* Update e2e tests.
> src/pages: show button loader when updating registration via API in RegisterChallengePage

- src/components/__tests__/RegisterChallengePayment.cy.js
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Add missing translated messages for API `getHasOrganizationAdmin` key.
> src/i18n: add translated messages for API getHasOrganizationAdmin

- src/i18n/en.toml
Fixes [Bug 26](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=26).
Update login button labels.
> src/i18n: update labels on login buttons

- src/components/__tests__/FormPersonalDetails.cy.js
- src/components/form/FormPersonalDetails.vue
Fixes [Bug 66](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=66).
Add link to personal data protection policy to `FormPersonalDetails`.
Link is defined in global config.
Add link test.
> src/components: add link to personal data protection policy to FormPersonalDetails

- ride_to_work_by_bike_config.toml
- src/components/global/TopBarCountdown.vue
- src/components/homepage/CountdownChallenge.vue
- src/components/homepage/CountdownEvent.vue
- src/composables/useCountdown.ts
- src/pages/IndexPage.vue
- src/stores/challenge.ts
- src/utils/index.ts
- test/cypress/e2e/home.spec.cy.js
Connect `CountdownEvent` component to challenge phase set data.
* Create a `getCompetitionStart` getter in `challenge` store.
* Get the competition start date in `IndexPage` and pass it down to `CountdownEvent`.
* Update `useCountdown` composable to handle dynamic data (`ComputedRef`).
Additionally, fix the E2E test for "before challenge" context (update template display conditions)
> src/components: connect CountdownEvent component to challenge phase set data

- src/components/__tests__/FormFieldSelectTable.cy.js
Fix subsidiary ZIP form field placeholder mask.
> src/components/__tests__: fix subsidiary ZIP form field placeholder mask

- src/components/__tests__/RegisterChallengePayment.cy.js
Instead of interception `interceptIsUserOrganizationAdminGetApi` request, beacuse this request is not made on the `RegisterChallengePayment` component level.
> src/components/__tests__: fix setting register challange isUserOrganizationAdmin store value

- src/components/__tests__/FormRegisterCoordinator.cy.js
- src/components/register/FormRegisterCoordinator.vue
Fixes [Bug 77](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=77).
Make privacy policy link in `FormRegisterCoordinator` component clickable.
Use `@click.stop` to stop propagation of the event to the checkbox label.
Add test which confirms the behaviour.
> src/components: make privacy policy link in FormRegisterCoordinator coordinator form clickable

- src/components/__tests__/LoginRegisterButtons.cy.js
- src/components/global/LoginRegisterButtons.vue
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Add social media login/register buttons hint text.
> src/components/global: add social media login/register buttons hint text

- src/pages/ChallengeInactivePage.vue
- test/cypress/e2e/challenge_inactive.spec.cy.js
* Remove dummy posts from `ChallengeInactivePage`
* Add helper element to stretch content to the full height of the page with `SocialBar` at the bottom.
> src/pages: remove dummy posts from ChallengeInactivePage

- src/components/__tests__/DrawerMenu.cy.js
- src/components/global/MobileBottomPanel.vue
- src/layouts/MainLayout.vue
- src/mocks/layout.ts
- test/cypress/e2e/community.spec.cy.js
- test/cypress/support/commonTests.ts
> src/mocks: fix getting global app config in Cypress e2e tests

- src/components/__tests__/FormRegister.cy.js
- src/components/register/FormRegister.vue
- test/cypress/e2e/register.spec.cy.js
On the registration URI page during all current challenge phases.
> src/components/register: fix showing accept data privacy policy checkbox element

- src/utils/price_levels.ts
- test/cypress/e2e/unit_utils_tests.cy.js
- test/cypress/fixtures/getCurrentPriceLevelsUtilTestData.json
Fix and extend `getCurrentPriceLevelsUtilTestData()` func by unit tests.
> src/utils: fix and extend getCurrentPriceLevelsUtilTestData() func by unit tests

- src/utils/price_levels.ts
- test/cypress/e2e/unit_utils_tests.cy.js
- test/cypress/fixtures/getCurrentPriceLevelsUtilTestData.json
Fix and extend Cypress e2e unit unit_utils_tests test file.
> src/utils: fix getting current price level calculation

- ride_to_work_by_bike_config.toml
- src/components/__tests__/FormFieldListMerch.cy.js
- src/components/form/FormFieldListMerch.vue
- src/components/types/Config.ts
- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
- test/cypress/e2e/register_challenge.spec.cy.js
Add merchandise size conversion chart URL link.
> src/components/form: add merchandise size conversion chart URL link

- src/pages/CompanyCoordinatorPage.vue
Global app config var:
- `urlRideToWorkByBikeOldFrontendDjangoApp`
> src/components: inject global app config var with localization lang code

- src/components/__tests__/FormRegister.cy.js
- src/components/register/FormRegister.vue
- test/cypress/support/commonTests.ts
Update notification text display condition in `FormRegister`.
* Do not show notification text during registration phase.
* Test behaviour in component test with new timestamp.
> src/components: fix showing registration notification text condition

- src/i18n/cs.toml
- src/i18n/en.toml
- src/i18n/sk.toml
Update translation string for offer verification. Text approved by O. H.
> src/i18n: update merchandise translation strings

- src/components/__tests__/RouteInputDistance.cy.js
- src/components/__tests__/RouteItemEdit.cy.js
- src/components/routes/RouteInputDistance.vue
Hide select option Draw on map in distance input.
Skip tests related to map select option.
> src/components/routes: disable trace to map action option menu item

- src/composables/useIsBeforeCompetitionPhase.ts
- src/pages/IndexPage.vue
- test/cypress/e2e/home.spec.cy.js
- test/cypress/support/commonTests.ts
Add condition for displaying `EventCountdown` component on `IndexPage`.
* Add `useIsBeforeCompetitionPhase` composable which checks every 5 seconds whether the competition phase has started
* Display `EventCountdown` on `IndexPage` based on the `isBeforeCompetitionStart` flag.
* Add E2E test for the behaviour.
> src/pages: add condition for displaying challenge event countdown element

- src/stores/results.ts
Fix showing Metabase regularity, organization/city performance data report for basic challenge member.
> src/stores: fix showing Metabase regularity, organization/city performance data report for basic challenge member

- src/adapters/registerChallengeAdapter.ts
- src/components/types/ApiRegistration.ts
- test/cypress/e2e/register_challenge.spec.cy.js
- test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsNoNickname.json
* Set default value for `nickname` field on API endpoint to `null` via the adapter.
* Test sending an empty nickname field.
> src/adapters: fix saving register-challenge/ REST API URL endpoint nickname field null value (#1007)

- src/stores/results.ts
Fix showing Metabase regularity, city performance data report for basic challenge member.
> src/stores: fix showing Metabase regularity, city performance data report for basic challenge member

- src/pages/IndexPage.vue
- test/cypress/e2e/home.spec.cy.js
Hide banner routes as it shows incorrect date on the final day of challenge.
> src/pages/IndexPage: hide banner Routes
