renovate.json
Enable CI Renovate bot instead of Dependency bot.
[https://github.com/apps/renovate
https://developer.mend.io/](https://developer.mend.io/)
=> Enable CI Renovate bot instead of Dependency bot

src/components/TheFooter.vue
Fix showing deployed frontend app version info into mobile viewport.
**Screenshots**
=> src/components: fix showing deployed frontend app version info into mobile viewport

src/components/TheFooter.vue, test/cypress/e2e/home.spec.cy.js, test/cypress/support/commands.js
* Provide unique identifiers for the two footer buttons in Cypress E2E test
* Double-up on .click() simulation - workaround for Resize Observer bug
Similar problem mentioned in another repo:
https://github.com/benetech/VideoDeduplication/issues/442
Screenshot: Example case where second click triggers the desired action after Error.
=> test/cypress/e2e: fix ResizeObserver loop completed with undelivered notifications error

src/components/FooterBar.vue, src/components/TheFooter.vue, src/components/__tests__/FooterBar.cy.js, src/layouts/MainLayout.vue
* Rename component `TheFooter` to `FooterBar` (Footer is a reserved HTML keyword)
* Fix alignment of social-link icons by adding `display: flex`
* Remove icon underline with `style` override (button has default hover behaviour)
=> src/components: rename component file name/name  plus fix icon alignment

src/components/__tests__/CardEvent.cy.js, src/components/__tests__/CardOffer.cy.js, src/components/__tests__/DrawerHeader.cy.js, src/components/__tests__/ListFaq.cy.js, src/components/__tests__/UserSelect.cy.js
* For selected components remove chaining `click().then(() => {...})`
See error: `It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from "cy." in a next command line.`
=> src/components/__tests__: split command chaining to fix eslint cypress plugin error

test/cypress/e2e/home.spec.cy.js
Error message:
```
test@test:/tmp/ride-to-work-by-bike-frontend$ yarn lint
yarn run v1.22.19
$ eslint --ext .js,.ts,.vue ./
/tmp/ride-to-work-by-bike-frontend/test/cypress/e2e/home.spec.cy.js
275:7   error  It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from `cy.` in a next command line  cypress/unsafe-to-chain-command @typescript-eslint/no-unused-vars                                                                                                                
540:7   error  It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from `cy.` in a next command line  cypress/unsafe-to-chain-command @typescript-eslint/no-unused-vars
```
=> test/cypress/e2e: fix Cypress e2e tests unsafe to chain command error message

tsconfig.json
Error message:
`TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.`
**Additional context**
Check the tests result of PR #40.
=> ts: fix run Cypress e2e unit tests with TypeScript version 5.0.0

src/components/SectionColumns.vue, src/components/SectionColumnsTest.vue, src/components/__tests__/SectionColumns.cy.js, src/mocks/homepage.ts, src/pages/IndexPage.vue
* Implements flexible grid component which allows to list component cards on homepage without the need to create separate `List` element.
* Uses slot and render functions to apply correct classes.
* In future it can replace several components such as `ListBadgeAchievement`, `ListCardChallenge`, or `ListCardEvent`.
* `SectionColumnsTest` component is created to easily render the content of slots within the standard Cypress component test.
* Component is used on `IndexPage` with `CardStats` as content.
=> src/components: add SectionColumns component

docker/Dockerfile, docker/dev/Dockerfile
Upgrade Docker Alpine GNU/Linux base image Node.js version to the last LTS Iron 20.x version.
=> docker: upgrade Node.js version to the last LTS Iron 20.x version

test/cypress/run_tests.sh
Fix Cy component/e2e tests execution if the `-s` flag is used.
Example:
```
yarn test:e2e:firefox -s test/cypress/e2e/unit_tests_app_code.spec.cy.js
```
=> test/cypress: fix Cy component/e2e tests execution if the -s flag is used

README.md, docker/dev/Dockerfile, docker/dev/install_app_dependencies.sh, docker/dev/install_custom_packages.sh
Use Ubuntu GNU/Linux Jammy Jellyfish 22.04 LTS version as Docker base image with latest Node.js LTS Iron 20.x version and lastest Mozilla Firefox, Google Chrome, Microsoft Edge web browser.
=> Fix run Cypress test framework from dev Dockerfile

quasar.config.js, src/components/__tests__/BadgeAchievement.cy.js, src/components/__tests__/BannerApp.cy.js, src/components/__tests__/BannerImage.cy.js, src/components/__tests__/BannerRoutes.cy.js, src/components/__tests__/CardChallenge.cy.js, src/components/__tests__/CardEvent.cy.js, src/components/__tests__/CardFollow.cy.js, src/components/__tests__/CardOffer.cy.js, src/components/__tests__/CardPost.cy.js, src/components/__tests__/CardProgress.cy.js, src/components/__tests__/CardProgressSlider.cy.js, src/components/__tests__/CardStats.cy.js, src/components/__tests__/DrawerHeader.cy.js, src/components/__tests__/FooterBar.cy.js, src/components/__tests__/FormLogin.cy.js, src/components/__tests__/HelpButton.cy.js, src/components/__tests__/ListCardFollow.cy.js, src/components/__tests__/ListCardOffer.cy.js, src/components/__tests__/ListCardPost.cy.js, src/components/__tests__/ListCardProgress.cy.js, src/components/__tests__/MenuLinks.cy.js, src/components/__tests__/NewsletterFeature.cy.js, src/components/__tests__/NewsletterItem.cy.js, src/components/__tests__/SliderProgress.cy.js
* Replace hard coded hex color values with `getPaletteColor` fn
* Shorten 6 character hex values to 3 character hex values
* Fix lint errors
=> src/components/__tests__: replace hex color definitions with getPaletteColor func

quasar.config.js, ride_to_work_by_bike_config.toml, src/boot/global_vars.js, src/components/BannerImage.vue, src/components/CountdownChallenge.vue, src/components/CountdownEvent.vue, src/components/FormLogin.vue, src/components/HelpButton.vue, src/components/LanguageSwitcher.vue, src/components/types/Config.ts, src/layouts/MainLayout.vue, src/pages/LoginPage.vue, src/utils/get_app_conf.js, test/cypress/support/component.js
* Add boot file `global_vars.js` for central color class override
* Add `colorBlack` and `colorWhite` to config
* Add color override function to `cypress/support/component.js` to sync color variables in component tests 
* Remove global config from components if imported for css var override
* Replace hex values of black and white colors in tests with `getPaletteColor` fn vars
Note: Overriden color value `info` cannot be imported using the `getPaletteColor` fn inside tests (it returns default Quasar value). Currently using config object for test comparison.
=> src/boot: declare global color config vars

src/components/CardProgress.vue
Tests in PR #121 fail on testing color in `CardProgress` component.
Element with `data-cy="card-progress-share"` should implicitly have text color set. However, browser does not seem to recognize this and renders it always with the same color (`rgb(67, 68, 156)`).
This change sets the color explicitly on the element.
=> src/components: fix 'card-progress-share' test by explicitly defining text color

test/cypress/e2e/login.spec.cy.js
In `login.spec.cy.js` make updates based on recent PRs:
* Use dynamic path from `routesConf`
* Use common testLanguageSwitcher() fn for testing the header language switcher
=> test/cypress/e2e: use dynamic path for login tests + refactor lang switch test

src/components/__tests__/FormFieldEmail.cy.js, src/components/__tests__/FormFieldPhone.cy.js, src/components/__tests__/FormRegister.cy.js, src/components/__tests__/FormRegisterCoordinator.cy.js, src/components/__tests__/HelpButton.cy.js, src/components/__tests__/LoginRegisterHeader.cy.js, src/components/global/ContactForm.vue, src/components/global/FormFieldPhone.vue, test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/login.spec.cy.js
Cypress test fix for automatic update in PR #181 
* use `.should('be.empty')` instead of `.should('not.be.visible')` for checking input error messages: this should be a more robust method in general as it relies on DOM content and not the message visibility implementation (CSS).
* update `rules` in `src/components/global/ContactForm.vue`: as the component was using outdated rules and tests pass for other input elements.
=> test/cypress/e2e: fix re-apply input widget lazy validation rules during component/e2e tests

test/cypress/e2e/register.spec.cy.js
Issue: `RegisterPage` is missing E2E test.
* Add `register.spec.cy.js` test file
Tests are kept to a minimum as all the components on the page are already tested.
=> test/cypress/e2e: add RegisterPage e2e tests

src/components/__tests__/FormFieldPassword.cy.js, src/components/__tests__/FormFieldPasswordConfirm.cy.js, src/components/__tests__/FormRegisterCoordinator.cy.js, src/components/global/FormFieldPassword.vue, src/components/global/FormFieldPasswordConfirm.vue, src/components/global/FormFieldTestWrapper.vue, src/components/register/FormRegisterCoordinator.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml
Issue: Password and Password confirm tests are duplicated across form components and their code repeats.
Solution:
* Refactor inputs into `FormFieldPassword` and `FormFieldPasswordConfirm` components
* Add a general testing wrapper for FormField components
* Refactor `FormRegisterCoordinator` component and tests
To do: Replace other FormField test wrapper components with `FormFieldTestWrapper`.
=> src/components/global: add `FormFieldPassword`, `FormFieldPasswordConfirm` components

src/components/__tests__/ContactForm.cy.js, src/components/__tests__/HelpButton.cy.js, src/components/__tests__/LoginRegisterHeader.cy.js, src/components/global/ContactForm.vue, src/components/global/FormFieldEmail.vue, test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/login.spec.cy.js
Use `FormFieldEmail` across all forms:
* Use component in `ContactForm`
* Remove duplicate tests from `ContactForm.cy.js`
* Update usage docs in `FormFieldEmail` component
=> components/global: use `FormFieldEmail` component across all forms

src/components/global/ContactForm.vue, src/components/global/FormFieldCompany.vue, src/components/global/FormFieldPassword.vue, src/components/global/FormFieldPasswordConfirm.vue, src/components/global/FormFieldTextRequired.vue, src/components/login/FormLogin.vue, src/components/register/FormRegister.vue, src/components/register/FormRegisterCoordinator.vue, src/css/app.scss, src/css/form.scss
Issue: Scoped style for input field border radius was repeated.
* Created global stylesheet `form.scss` for form styles
* Added global rule for border radius
* Removed SFC scoped styles from form field components
=> src/css/form: add global border radius style

src/assets/svg/numeric-7-fill.svg, src/components/__tests__/FormCardMerch.cy.js, src/components/__tests__/FormFieldListMerch.cy.js, src/components/form/FormCardMerch.vue, src/components/form/FormFieldListMerch.vue, src/components/types/Form.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/cardMerch.json
Add registration step for selecting merchandise option.
Uses two components:
* `FormFieldListMerch` - displays list of option cards and handles logic
* `FormCardMerch` - displays single option (dialog included)
Includes step number `7` in `RegisterChallengePage`
Next PR: Add customization form for each merchandise option (shows inside the dialog).
=> src/components/form: add components to select merch in challenge registration

src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/form/FormAddCompany.vue, src/components/form/FormFieldCompanyAddress.vue, src/components/global/FormFieldCompany.vue, src/components/types/Form.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js
Add `FormFieldCompanyAddress` component (similar to `FormFieldCompany` but without select lookup).
* Add tests
Rename type `FormAddCompanyFields` to `FormCompanyFields` as it should label general Company model (within forms) not only the case of adding a new company.
=> src/components/form: add `FormFieldCompanyAddress` to challenge registration

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormAddCompany.vue, src/components/form/FormAddTeam.vue, src/components/form/FormFieldSelectTable.vue, src/components/types/Form.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/teamOptions.json
Registration challenge - Step 6 "Team"
Add `FormAddTeam` to display the contents of the "new team" dialog.
This component is used within `FormFieldSelectTable` in its `team` variant.
* Add tests for the `team` context in `FormFieldSelectTable.cy.js`.
* Add teamOptions fixture.
* Add translations.
=> components/form: add form for new team dialog

ride_to_work_by_bike_config.toml, src/boot/global_vars.ts, src/components/__tests__/TopBarCountdown.cy.js, src/components/global/TopBarCountdown.vue, src/components/types/Config.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/mocks/homepage.ts, src/pages/IndexPage.vue, src/pages/RegisterChallengePage.vue, src/utils/get_app_conf.js, test/cypress/e2e/register_challenge.spec.cy.js
To display countdown to start of a challenge in top bar this PR introduces following updates:
* Set challengeStartDate as a variable in `ride_to_work_by_bike_config.toml`
* Use this variable in components supporting countdown (makes use of `useCountdown` composable)
* Remove previously used mock data for the challenge start date
* Create new component `src/components/global/TopBarCountdown.vue` to display top bar
* Show the component on `src/pages/RegisterChallengePage.vue`
* Add translations (depending on the month of the challenge - also set in global config)
=> components/global: add bar component with challenge start countdown

src/components/__tests__/FormPersonalDetails.cy.js, src/components/form/FormPersonalDetails.vue
Solves issue #322 - Clicking on the checkbox label text link triggers checkbox widget event instead of opening link.
Solution:
* In `FormPersonalDetails` add `@click.stop` to stop event propagation.
* Add test which checks for checkbox value before and after link click.
=> components/form: fix link behavior within checkbox label

src/components/__tests__/FormFieldPhone.cy.js
Prevent recurrent issue in the test suit when tesing the `FormFieldPhone` component.
Logged error:
`AssertionError: Timed out retrying after 60000ms: expected '<div.q-field__messages.col>' to be 'visible'
This is likely caused by the messages element being animated.`
This change places .blur() method in between type method and subsequent evaluation. This has previously helped with resolving similar issues.
=> src/components/__tests__: add blur event to phone input validation tests to prevent test failure

src/components/__tests__/ResultsChallengeOngoing.cy.js, src/components/__tests__/ResultsChallengeUpcoming.cy.js, src/components/homepage/CardChallenge.vue, src/components/results/ResultsChallengeOngoing.vue, src/components/results/ResultsChallengeUpcoming.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/mocks/layout.ts, src/pages/ResultsPage.vue, src/router/routes.ts, src/router/routes_conf.ts, test/cypress/e2e/results.spec.cy.js
Adds `/results` route as `src/pages/ResultsPage.vue`
ResultsPage will be displaying different variants of content based on the challenge state. State variable source is to be implemented.
* Create `ResultsChallengeOngoing.vue`
* Create `ResultsChallengeUpcoming.vue`
These store the content for the variants.
* E2E results spec tests the "challenge upcoming" variant.
* Mocks (same as on homepage) are used to render content.
=> src/pages: add Results Page with variants of content

src/components/__tests__/ResultsTabs.cy.js, src/components/results/ResultsTabs.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/ResultsDetailPage.vue, src/router/routes.ts, src/router/routes_conf.ts, test/cypress/e2e/results_detail.spec.cy.js
Adding a results detail page:
* `ResultsDetailPage` to show results for an individual user
* `RoutesTabs` component to switch between different tabs on results page
* new routes for different tabs to `routes_conf`
* translations
=> src/pages: add ResultsDetailPage with tabs component

test/cypress/e2e/routes.spec.cy.js
Steps to fix failing test in `routes` E2E test.
* Test route `/routes/calendar` as the default view for the tab component (identical content - avoids redirection).
* Wrap test into `cy.window().then()` callback to allow for window to load before running tests.
=> test/cypress/e2e: update test for routes

test/cypress/e2e/register_challenge.spec.cy.js
Issue: register_challenge e2e test is failing because title is being compared to `translation key` as opposed to translation string (resulting text).
To prevent this, new code:
1. determines the month option 
2. retrieves full string translation
All this before the comparison runs.
=> test/cypress/e2e: fix E2E test register_challenge translation string

src/components/__tests__/CardOffer.cy.js, test/cypress/support/commands.js
Fix issue where width test incorrectly subtracts scroll sidebar width from children percentage width.
This allows to correctly pass 100% width in cases where content overflows.
Needed to make PR #408 pass.
=> test/cypress/support/commands: fix inconsistency in width test

test/cypress/e2e/register_challenge.spec.cy.js
Problem: E2E tests continue to fail on translations (expecting translation key instead of translated string).
The attempt to fix this is introducing `cy.wrap` to yield the evaluated translation into the `.then` callback.
Described in docs: https://docs.cypress.io/api/commands/wrap
=> test/cypress/e2e/register_challenge: use cy.wrap to yield translation value before evaluation

src/components/__tests__/BreadcrumbTitle.cy.js, src/components/global/BreadcrumbTitle.vue, src/components/types/Breadcrumb.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/ResultsDetailPage.vue, src/router/routes.ts, test/cypress/e2e/results_detail.spec.cy.js
Add BreadcrumbTitle component for displaying the title of the current page with breadcrumb.
* Breadcrumb is loaded from `route` object, predefined in `routes` file based on `routes_conf` file data.
* Pages are dynamically added within the component.
* Page titles in breadcrumb are translated based on the route `name` via i18n with translation key `breadcrumb`.
=> src/components/global: add component BreadcrumbTitle for rendering titles of subpages

test/cypress/e2e/routes.spec.cy.js
Issue: E2E tests sometimes fail on checking the content of the TabPanel component from Quasar.
This may be caused by the redirection of the `routes` path to `routes_calendar`, which secures the initial state for the tab component.
* Use `routes_calendar` config route to avoid redirection when tests are loaded (already implemented for desktop).
=> test/cypress/e2e: fix failing routes test by avoiding redirection

src/components/__tests__/ListCardFollow.cy.js, src/components/__tests__/ListCardOffer.cy.js, src/components/__tests__/ListCardPost.cy.js, src/components/__tests__/ListCardProgress.cy.js, src/components/__tests__/ListCardSlider.cy.js, src/components/__tests__/NewsletterFeature.cy.js, src/components/__tests__/ResultsList.cy.js, src/components/__tests__/RoutesApps.cy.js, src/components/__tests__/RoutesBottomPanel.cy.js, src/components/__tests__/SectionHeading.cy.js, src/components/__tests__/SliderProgress.cy.js, src/components/global/ListCardSlider.vue, src/components/global/SectionHeading.vue, src/components/homepage/ListCardFollow.vue, src/components/homepage/ListCardOffer.vue, src/components/homepage/ListCardPost.vue, src/components/homepage/ListCardProgress.vue, src/components/homepage/NewsletterFeature.vue, src/components/homepage/SliderProgress.vue, src/components/results/ResultsChallengeOngoing.vue, src/components/results/ResultsChallengeUpcoming.vue, src/components/results/ResultsList.vue, src/components/routes/RoutesApps.vue, src/components/routes/RoutesBottomPanel.vue, src/pages/CommunityPage.vue, src/pages/IndexPage.vue, src/pages/PrizesPage.vue, test/cypress/e2e/community.spec.cy.js, test/cypress/e2e/prizes.spec.cy.js
Create central setting for a section heading (h2) via a component.
* Replace h2 headings with the same styling by the component across the codebase.
* When needed, update tests to use component CY handles.
=> src/components/global: refactor headings with new component SectionHeading

src/components/__tests__/HeaderOrganization.cy.js, src/components/coordinator/HeaderOrganization.vue, src/components/types/Organization.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/headerOrganization.json
Add component `HeaderOrganization` with basic information about an organization.
This is shown on the company coordinator page above the team/members table.
* Add fixture
* Add types `Organization`, `OrganizationMember` and `OrganizationBranch` (these may be extended in the future)
* Add tests
=> src/components/coordinator: add component HeaderOrganization to display info on coordinator page

src/components/__tests__/BannerInfo.cy.js, src/components/global/BannerInfo.vue, test/cypress/fixtures/bannerInfo.json
Add component BannerInfo to show info boxes. Used on `CompanyCoordinatorPage`.
Title and icon are passed through props and content through slot for flexibility.
* Add fixture
* Add tests
=> src/components/global: add component BannerInfo to display general info component

src/components/global/BreadcrumbTitle.vue, src/components/global/DrawerMenu.vue, src/components/global/MobileBottomPanel.vue, src/mocks/layout.ts, src/router/routes.ts, src/router/routes_conf.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/e2e/register_coordinator.spec.cy.js, test/cypress/e2e/results_detail.spec.cy.js, test/cypress/e2e/routes.spec.cy.js
Issue: Definition of routes does not provide a clear hierarchical structure (within the `route.matched` array).
Routes defined within `routes.ts` are duplicated and do not make use of nesting.
Nest routes in `routes.ts` for example:
* results
* detail
* report
* regularity
* ...
Fix naming inconsistencies in route keys (`-` -> `_`).
Update navigation components to use urls resolved from router using route name.
Update breadcrumb element to use `matched` array in addition to custom breadcrumb.
=> src/router: refactor the nested routes definition

src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RoutesCalendar.vue, src/components/types/Route.ts
Currently, only one calendar route can be active at a time.
To enable the option of selecting multiple routes at once:
* store active routes in `activeRoutes` array
* update isActive checks
* update tests so that they check active/inactive state for multiple calendar routes at a time.
=> src/components/routes: enable active calendar routes multivalue

.husky/pre-commit, src/components/__tests__/FormFieldCheckboxRequired.cy.js, src/components/__tests__/FormFieldCheckboxTeam.cy.js, src/components/__tests__/FormRegisterCoordinator.cy.js, src/components/form/FormFieldCheckboxRequired.vue, src/components/global/FormFieldTestWrapper.vue, src/components/register/FormRegisterCoordinator.vue, src/css/form.scss
Add component `FormFieldCheckboxRequired` to simplify the use of required checkboxes (consents etc.) across codebase.
This is used in `FormRegisterCoordinator` and will be used in `RegisterChallengePayment` - payment step of challenge registration.
* Add a new component.
* Add tests (display + validation).
* Update FormFieldTestWrapper component to handle passing boolean value, validation messages and slots.
* Move styles for checkbox to global CSS.
=> src/components/form: add component FormFieldCheckboxRequired to refactor forms

src/components/coordinator/TaskListCoordinator.vue
Fix eslint error in `TaskListCoordinator` component.
Error appears in eslint v8 and prevents tests in PR #496 from passing.
Replaces ternary operator short-hand with `if-else` code.
=> src/components: fix eslint error in TaskListCoordinator component

src/components/routes/RouteTabs.vue, src/components/types/Route.ts
Replace RouteTab names (type) with TS enum.
Use enums in `RouteTabs` component.
=> src/components/routes: replace route tab names with enums

ride_to_work_by_bike_config.toml, src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RoutesCalendar.vue, src/components/types/Config.ts, src/composables/useCalendarRoutes.ts, src/utils/get_app_conf.js
Updates behaviour of selecting routes in Calendar:
* User can only select routes within X days in the past (defined in global config)
* If a route is logged (user data saved) it can only be selected individually
* If empty routes are selected and user click on logged route, all other routes are deselected
* If logged route is selected and user clicks on empty route, logged route is deselected
Refactored the route-selection behaviour into a new composable `useCalendarRoutes.ts`.
Disabled eslint rule which prevented from using require in `get_app_conf.js` (this is necessary as we are not using `"type": "module"` in package.json)
=> src/components/routes: update route selection behaviour in RoutesCalendar component

ride_to_work_by_bike_config.toml, src/components/__tests__/RouteCalendarPanel.cy.js, src/components/__tests__/RouteListDisplay.cy.js, src/components/__tests__/RouteListEdit.cy.js, src/components/routes/RouteItemEdit.vue, src/components/routes/RouteListDisplay.vue, src/components/routes/RouteListEdit.vue, src/components/types/Route.ts, src/composables/useLogRoutes.ts, src/composables/useRoutes.ts, test/cypress/fixtures/routeEmpty.json, test/cypress/fixtures/routeList.json
Update behaviour of RouteList components
Specification:
* Always render all routes for an active challenge
* Based on config, render X routes which are editable (`RouteListEdit` component)
* Render the rest of the routes as not editable (`RouteListDisplay` component)
* Logged routes data loaded from DB are integrated into the view
Refactored `getDays` method in `useRoutes.ts` composable to create an array of days with route data.
Updated old `RouteListDay` data structure to mirror the one used in Calendar (using `toWork` and `fromWork` parameters)
Added config settings and updated list components to use them.
Updated tests.
=> src/components/routes: update RouteList components' behaviour

quasar.config.js, src/boot/pinia.js
Register Pinia Vue store JS lib.
Fixes error message:
```
Uncaught (in promise) Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Are you trying to use a store before calling "app.use(pinia)"?
See https://pinia.vuejs.org/core-concepts/outside-component-usage.html for help.
This will fail in production.
```
=> src/boot: register Pinia Vue store JS lib

src/components/__tests__/TaskListCoordinator.cy.js
Tests for `TaskListCoordinator` currently fail because the date is not set before component initialization.
Update time setting so that `clock` sets date before component initialization.
Cy components tests error message:
```
<TaskListCoordinator>
✓ has translation for all strings (35ms)
desktop
1) renders component
2) allows to show past tasks
mobile
3) renders component
4) allows to show past tasks
1 passing (4m)
4 failing
1) <TaskListCoordinator>
desktop
renders component:
AssertionError: Timed out retrying after 60000ms: Not enough elements found. Found '2', expected '3'.
-2
+3
at coreTests/ (/home/runner/work/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/src/components/__tests__/TaskListCoordinator.cy.js:59:10)
at getRet …
```
=> src/components/__tests__: correct time setting in TaskListCoordinator tests

src/components/__tests__/TableNotifications.cy.js, src/components/profile/ProfileTabs.vue, src/components/profile/TableNotifications.vue, src/components/types/Notifications.ts, src/components/types/Table.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/tableNotifications.json
Add component `TableNotifications` for displaying user notifications on Profile page.
* Add Quasar table with custom slots.
* Add `Notification` type based on [Notification API endpoint](https://dpnk.dopracenakole.cz/rest/notification/).
* Add `TableColumn` type to emulate Quasar table prop types and prevent typescript error.
* Add tests
=> src/components: add component TableNotifications for displaying user notifications

package.json, src/utils/get_app_conf.js, src/utils/get_deployed_app_version.js, yarn.lock
To fix Quasar framework Vite pre bundle error:
```
✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-0a035c79.js:40970:10:
40970 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
╵           ^
at packageEntryFailure (/home/tomas/auto_mat_software/msimon/ride-to-work-by-bike-frontend/node_modules/vite/dist/node/chunks/dep-0a035c79.js:40970:11)
at resolvePackageEntry (/home/tomas/auto_mat_software/msimon/ride-to-work-by-bike-frontend/node_modules/vite/dist/node/chunks/dep-0a035c79.js:40966:9)
at …
```
=> src/utils: replace JS fs package with fs-extra package

test/cypress/e2e/profile.spec.cy.js
Update selectors in the `profile` E2E test - `drawer-menu` got replaced with `drawer-menu-top` and `drawer-menu-bottom`
=> test/cypress/e2e: fix profile e2e test by testing new menu selectors

test/cypress/support/commands.js
Issue: In `FormLogin`, some tests did not pass, because the English strings that other translations are compared to were not correctly reset using `global.locale`. This change fixes the issue.
=> test/cypress/support: fix command for testing translation strings

ride_to_work_by_bike_config.toml
Prevent automatically add missing / on the end of URL by backend and redirect original POST request to modified URL with GET request type, which cause backend REST API login HTTP 405 Method Not Allowed error and endpoint return JSON data `{"detail":"Metoda \"GET\" není povolena."}`
Login REST API URL endpoint rest/auth/login/ accept POST, OPTIONS request method type.
=> Fix REST API login URL missing / on the end of URL path

src/components/__tests__/DrawerToggleButtons.cy.js, src/layouts/MainLayout.vue, test/cypress/e2e/community.spec.cy.js, test/cypress/support/commonTests.ts
Remove button to toggle city admin view from MainLayout.
City admin view is not currently available.
=> src/layouts: remove button to toggle city admin view from MainLayout

src/components/__tests__/BreadcrumbTitle.cy.js, src/components/__tests__/PageHeading.cy.js, src/components/global/BreadcrumbTitle.vue, src/components/global/PageHeading.vue, src/pages/CommunityPage.vue, src/pages/CompanyCoordinatorPage.vue, src/pages/IndexPage.vue, src/pages/PrizesPage.vue, src/pages/ProfilePage.vue, src/pages/ResultsDetailPage.vue, src/pages/ResultsPage.vue, src/pages/RoutesPage.vue, test/cypress/e2e/community.spec.cy.js, test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/prizes.spec.cy.js
Add component `PageHeading` to unify styling across the content pages.
Accommodates for the following use cases:
* Additional content below the title.
* Additional content on the same row as title (flexed to the right) - uses the `horizontal` prop.
* Allows to be used with `BreadcrumbTitle` component, showing breadcrumb on nested pages.
Updates E2E tests where appropriate to only check for content and not styling.
=> src/components: add component PageHeading for all content pages

test/cypress/support/commonTests.ts
Add visibility check before click in UserSelect e2e test.
This should help preventing the occasional failures of this test due to button not being clickable.
=> test/cypress/support: add visibility check before click in UserSelect e2e test

ride_to_work_by_bike_config.toml, src/components/__tests__/BannerAppButtons.cy.js, src/components/__tests__/EmailVerification.cy.js, src/components/__tests__/FormLogin.cy.js, src/components/__tests__/FormRegister.cy.js, src/components/login/BannerAppButtons.vue, src/components/login/FormLogin.vue, src/components/register/EmailVerification.vue, src/components/register/FormRegister.vue, src/components/types/Config.ts, src/utils/get_app_conf.js
Update the approach to getting a white background color with opacity.
* Define shared variable opacity in config.
* Use opacity to derive whiteOpacity color in components.
* Change color of text in white box on login screen.
* Unify color of separators on login and register screens and add tests.
Unifies inconsistency in design file:
1. [white email icon on white background 20%](https://www.figma.com/design/L8dVREySVXxh3X12TcFDdR/Do-pr%C3%A1ce-na-kole?node-id=6269-24822&t=Kg5tEX1Skno3i6DW-1)
2. [blue email icon on white background 50%](https://www.figma.com/design/L8dVREySVXxh3X12TcFDdR/Do-pr%C3%A1ce-na-kole?node-id=6385-26491&t=Kg5tEX1Skno3i6DW-1)
Renders all instances of given icon as variant 1.
=> config: update and unify the white background color from config

src/components/__tests__/FooterBar.cy.js, test/cypress/support/commonTests.ts
In `FooterBar` tests, add `User-Agent` header to fix response code value of the `cy.request`.
=> src/components/__tests__: fix request header when requesting Facebook URL in FooterBar tests

src/components/__tests__/ProfileCoordinatorContact.cy.js
Solves issue where avatar snapshot would be taken while still showing the placeholder image.
If image has `src`, placeholder is being shown until the image is loading (together with a loader element)
We wait until the loader element does not exist to take the snapshot.
This should prevent the `ProfileCoordinatorContact` component test from failing occasionally.
Error message (OS MS Windows, Google Chrome web browser):
```
1 failing
1) <ProfileCoordinatorContact>
desktop
renders avatar of a company coordinator:
Error: Image was 23.756377551020407% different from saved snapshot with 745 different pixels.
See diff for details: D:\a\ride-to-work-by-bike-frontend\ride-to-work-by-bike-frontend\test\cypress\snapshots\ProfileCoordinatorContact.cy.js\__diff_output__\ProfileCoordinatorContact -- …
```
=> src/components/__tests__: ProfileCoordinatorContact wait for image load before snapshot

src/components/__tests__/LoginRegisterHeader.cy.js, src/components/__tests__/LoginRegisterMobileMenu.cy.js, src/components/global/LoginRegisterHeader.vue, src/components/global/LoginRegisterMobileMenu.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/utils/index.ts
Add component `LoginRegisterMobileMenu` to display responsive header in the login-register layout.
* Adds the new component (integrating `HelpButton` and `LanguageSwitcher` components).
* Used component in `LoginRegisterHeader` based on screen size.
* Add translation strings.
* Add tests.
=> src/components: add component LoginRegisterMobileMenu for responsive header

test/cypress/fixtures/loginResponse.json
Add missing login response fixture JSON file.
Fixes error message:
```
1 failing
1) <LoginRegisterMobileMenu>
logged in
"before each" hook for "renders component":
Error: A fixture file could not be found at any of the following paths:
> test/cypress/fixtures/loginResponse.json
> test/cypress/fixtures/loginResponse.json.[ext]
Cypress looked for these file extensions at the provided path:
> .json, .js, .coffee, .html, .txt, .csv, .png, .jpg, .jpeg, .gif, .tif, .tiff, .zip
Provide a path to an existing fixture file.
```
=> test/cypress/fixtures: add missing login response fixture JSON file

src/components/__tests__/TableFeeApproval.cy.js, src/components/coordinator/TableFeeApproval.vue, src/components/types/Table.ts, src/composables/useTable.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/tableFeeApproval.json
Add table of pending entry fee payments for approval to be shown on company coordinator page.
* Define columns
* Predefine optional custom sorting function
* Add labels
* Enabled sorting by date (date timestamp) - perhaps by using timestamp in the data source
* Implemented a pre-sort to display "team headings"
=> src/components/coordinator: add component TableFeeApproval for coordinator page

src/components/register/EmailVerification.vue, src/stores/login.ts, test/cypress/e2e/register.spec.cy.js
Add logout and redirect action to the 'register again' link in EmailVerification.
This ensures that user can access register page and register again with a different email.
=> src/components: add logout and redirect action to the 'register again' link in EmailVerification

src/components/__tests__/FormFieldCompany.cy.js
Update `FormFieldCompany` tests using vModelAdapter.
This allows direct access to `modelValue` variable in tests.
It will also enable testing an upcoming change disabling `vatId` input for given situations.
Additionally, cleanup the use of selectors in checking for displayed error messages.
=> src/components/__tests__: update FormFieldCompany tests using vModelAdapter

src/components/__tests__/ListCardProgress.cy.js, src/components/homepage/ListCardProgress.vue
Issue: `StatsBar` in the `ListCardProgress` component shows 4 items instead of 3.
Solution: Using an array of ids, select stats displayed by the `StatsBar` in the `ListCardProgress` component.
Add test for the item count.
=> src/components: select stats shown by ListCardProgress and test count

src/components/global/MenuLinks.vue
Issue: `MenuLinks` social link URLs are not drawn from global config.
Use `useSocialLinks` composable which builds a list of links using the global config.
Tweak template for the use case.
=> src/components: pull MenuLinks social data from useSocialLinks composable

src/components/__tests__/MenuLinks.cy.js
Remove unnecessary translation function in `MenuLinks` component test, causing the tests to fail.
=> src/components/__tests__: remove unnecessary translation function in MenuLinks test

test/cypress/e2e/home.spec.cy.js
Remove incorrectly used `only` function.
=> test/cypress/e2e: remove "only" function from home E2E tests

src/components/__tests__/FormFieldNewsletter.cy.js
Issue: `nextTick().then()` results in tests not being evaluated in correct sequence.
* Fix improper use of `nextTick` function in `FormFieldNewsletter` component tests.
* In test `deselects all options when "all" is unclicked`, use UI interactions to get to the desired starting state to avoid failure.
* Note: initial state `model.value = [];` must be set within each test (not in the `beforeEach` hook) otherwise, it is not correctly loaded).
=> src/components/__tests__: fix FormFieldNewsletter component tests

src/components/__tests__/FormRegister.cy.js
Issue: Tests for `FormRegister` occasionally fail with following message:
```
1) <FormRegister>
no active challenge
allows to submit form after filling fields:
AssertionError: expected '' to equal 'foo@bar.org'
+'foo@bar.org'
```
Solution:
* Initiate store variable at the beginning of the test and pass the instance into the `compareRegisterResponseWithStore` function when needed.
* Add `nextTick` function before checking the store state.
=> src/components/__tests__: update initiation timing for store variables in FormRegister component tests

src/components/form/FormPersonalDetails.vue, src/components/types/Form.ts, src/components/types/RegisterChallenge.ts, src/stores/registerChallenge.ts
Add new types in `RegisterChallenge.ts` for handling the personal details section.
In the type used on FE, several type properties are marked as "not optional" so that they correctly work with input elements.
In the type used for API, these are marked as optional, based on the BE model.
Removes `email` field from the store data, as this is not part of the type.
Distinguishes the placement of the `newsletter` variable in local data structure and in API data structure.
=> src/components/types: add RegisterChallenge types for personal details section 

src/stores/challenge.ts
Fix printing date and time in human readable format.
Browser web console debug info:
```
12:41:08.208 debug |  q-cache/vite/spa/deps/pinia |  <registration> phase date from <1721001600000>. vue3-logger.ts:91:23
12:41:08.208 debug |  q-cache/vite/spa/deps/pinia |  <registration> phase date to <1727568000000>. vue3-logger.ts:91:23
12:41:08.208 debug |  q-cache/vite/spa/deps/pinia |  Now date <1731238868208>.
```
Expected debug info with human readable date and time format:
```
12:42:44.976 debug |  q-cache/vite/spa/deps/pinia |  <competition> phase date from <16 Sep 2024 2:0:0>. vue3-logger.ts:91:23
12:42:44.976 debug |  q-cache/vite/spa/deps/pinia |  <competition> phase date to <29 Sep 2024 2:0:0>. vue3-logger.ts:91:23
12:42:44.976 debug |  q-cache/vite/spa/deps/pinia |  Current date and …
```
=> src/stores: fix printing date and time in human readable format

ride_to_work_by_bike_config.toml
Remove additional `/rest` component of the endpoint URLs for challenge registration.
=> config: fix incorrect url paths for challenge api endpoints

src/utils/get_app_conf.js
With global ENV variables values.
Read global app config file variables names and convert them to theirs globals ENV variables equivalents names e.g. `'colorPrimary'` -> `'COLOR_PRIMARY'`.
=> src/utils: refactor overriding global app config file variables values

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormFieldSelectTable.vue, src/components/form/FormSelectOrganization.vue, src/components/types/Organization.ts, src/pages/RegisterChallengePage.vue
Issue: `FormFieldSelectTable` `variant` prop combines `OrganizationType` with and `team` option.
The table could also be used to filter and select `subsidiary`.
Solution:
* Add enum `OrganizationLevel` which distinguishes `organization`, `subsidiary` and `team`.
* In `FormFieldSelectTable` use `organizationLevel` and `organizationType` props instead of `variant`.
* Update usage in components `FormSelectOrganization` and `RegisterChallengePage`.
* Update prop usage in component tests.
Additionally, fix type of the variable `team` in `RegisterChallengePage` (this will be replaced by store value in a future PR).
=> src/components: fix prop types in FormFieldSelectTable component

test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/login.spec.cy.js, test/cypress/e2e/register.spec.cy.js, test/cypress/e2e/router_rules.cy.js, test/cypress/support/commonTests.ts
Issue: when `cy.clock` is used in tests, some parts of UI become unresponsive.
Clock function overrides the `setTimeout` and other time-related methods and if components are dependent on them, they do not work as expected.
Example problem:
```
1) Register page
inactive challenge
shows error message on registration failure:
AssertionError: Timed out retrying after 60000ms: expected '<div.q-notification__message.col>' to be 'visible'
```
Solution:
Based on [GitHub Issue](https://github.com/cypress-io/cypress/issues/7455#issuecomment-635278631), explicitly select functions and object which should be controlled by cypress clock command.
Mostly, this is only the `Date` function to set the reference time for token validity.
This allows to run most tests without calling `cy.tick(1000)` for …
=> test/cypress/e2e: add scope to cy.clock function to prevent issues with unresponsive UI elements

src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormSelectOrganization.vue, src/components/types/Organization.ts, src/composables/useSelectedOrganization.ts, src/composables/useValidation.ts
Issue: Currently, the `FormFieldCompanyAddress` component accepts `number` type ID as the `modelValue` prop. However, in data, this will be the object with address fields - value needs to correspond with subsidiary address so that we can determine `subsidiaryId`.
Solution:
* Update type in `FormFieldCompanyAddress` component
* Update calculating option values in `useSelectedOrganization` composable and add behaviour that sets `subsidiaryId` based on selected address.
Additionally, based on data from endpoint, add optional `address` pro to `Organization` type.
=> src/components: update FormFieldCompanyAddress v-model type

src/stores/login.ts, test/cypress/e2e/register.spec.cy.js
This change is up for discussion. Store is currently working as expected: Replacing user with an empty object.
This is most likely because we always mutate the `user` object as a whole.
However, based on JS logic (referencing a common object), if we mutate props individually, they get updated in the `emptyObject` which is pointed to by reference.
To prevent a possible issue in the future, I suggest using the deep object copy util, to never point by reference to the empty state.
Additionally, add a test for logout button visibility after logout.
=> src/stores: set empty user in login store via deep object copy function

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormFieldSelectTable.vue, src/components/form/FormSelectOrganization.vue, src/composables/useSelectTable.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue
Refactor dynamic labels in `FormFieldSelectTable` to a composable `useSelectTable`.
This simplifies the usage of the component (no need to specify all the props on multiple places).
Update docs example.
Note: The `subsidiary` version is not currently used but translation strings and tests are provided for completeness.
=> src/components: refactor dynamic labels in FormFieldSelectTable to a composable

src/components/__tests__/FormFieldCompany.cy.js, src/components/global/FormFieldCompany.vue
Issue: `FormFieldCompany` test occasionally fails on value check.
```
<FormFieldCompany>
desktop
allows user to select option:
Timed out retrying after 60000ms
```
Solution:
* Reset `model` variable before every test.
* Update value check based on used fixture and `model` variable while using `nextTick` for synchronicity.
=> src/components/__tests__: fix running FormFieldCompany tests after load Cypress JSON fixture (sync mode)  (#701)

src/components/__tests__/FormFieldCompany.cy.js
Issue: Component test for `FormFieldCompany` occasionally fails with message:
```
1) <FormFieldCompany>
desktop
allows to search through options:
AssertionError: Timed out retrying after 60000ms: expected '<div#f_9409d467-5078-4ac6-9962-587d04fbbf26_lb.q-menu.q-position-engine.scroll>' to be 'visible'
This element `<div#f_9409d467-5078-4ac6-9962-587d04fbbf26_lb.q-menu.q-position-engine.scroll>` is not visible because it has CSS property: `visibility: collapse`
```
Solution:
* Run cypress commands **after** closing of the `.then()` function which follows awaiting API request and interception checks).
=> src/components/__tests__: fix run Cypress command serially in FormFieldCompany component tests

src/components/__tests__/FormRegisterCoordinator.cy.js
Issue: `FormRegisterCoordinator` component tests occasionally fail with following problems:
```
1) <FormRegisterCoordinator>
desktop
validates checkboxes correctly:
AssertionError: Timed out retrying after 60000ms: Expected to find element: `.q-field__messages`, but never found it. 
...
2) <FormRegisterCoordinator>
desktop
submits form correctly:
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `registerCoordinator`. No request ever occurred.
```
Solution:
1. Switch to a more robust check for UI messages using `cy.contains` to find element by content.
2. Update sequencing of tests, placing the `compareRegisterResponseWithStore` function to its own `.then` block (also add `nextTick` function before checking for store …
=> src/components/__tests__:  fix FormRegisterCoordinator component command sequencing and message visibility checks

src/components/__tests__/CardFollow.cy.js, src/components/homepage/CardFollow.vue
Issue: `CardFollow` test occasionally fails with the following message:
```
1) <CardFollow>
desktop
renders image:
AssertionError: Timed out retrying after 60000ms: Expected to find element: `img`, but never found it. Queried from:
> cy.get([data-cy=card-follow-image], [object Object])
at Context.<anonymous> (D:/a/ride-to-work-by-bike-frontend/ride-to-work-by-bike-frontend/src/components/__tests__/CardFollow.cy.js:151:12)
```
Solution:
Wait for `CardFollow` image loader to not exist, to ensure `img` element existence before testing height and taking a snapshot.
=> src/components/__tests__: await CardFollow image load before testing height and taking snapshot

src/components/__tests__/FormFieldVoucher.cy.js, src/components/__tests__/RegisterChallengePayment.cy.js, src/components/form/FormFieldVoucher.vue, src/components/register/RegisterChallengePayment.vue
Issue: switching between payment subjects (e.g. `individual` and `voucher`) clears the voucher info box and instead, shows input again.
Solution:
* Add `activeVoucher` prop to `FormFieldVoucher` so we can pass voucher info by default.
* In `RegisterChallengePayment` component, store activeVoucher value and pass it into the `FormFieldVoucher` component (on init - when switching subjects).
* Add tests for this behaviour.
Note: Subsequent PR will address showing correct min. prices when switching between subjects.
=> src/components: in FormFieldVoucher add activeVoucher prop to show voucher info

src/i18n/index.js
Fix web browser console warning message:
```
[intlify] Not found 'monthYear' key in 'en' locale messages.
```
Screenshot:
App URL page: /#/coordinator/tasks/
=> src/i18n: fix waiting for reading locales files content

.github/workflows/run_tests.yaml, cypress.config.js, package.json, test/cypress/support/component.js, test/cypress/support/e2e.js, yarn.lock
Plugin for Cypress that adds better terminal output for easier debugging.
https://www.npmjs.com/package/cypress-terminal-report
Plugin is configured to log individual component/e2e tests files into individual test log files saved into root log test/cypress/logs/ directory.
=> test/cypress/support: add Cypress cypress-terminal-report plugin

src/components/__tests__/FormAddCompany.cy.js, src/components/__tests__/FormAddSubsidiary.cy.js, src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/__tests__/FormFieldSelectTable.cy.js, src/components/enums/Form.ts, src/components/form/FormAddCompany.vue, src/components/form/FormAddSubsidiary.vue, src/components/form/FormFieldCompanyAddress.vue, src/components/global/FormFieldCompany.vue, src/components/types/Form.ts, test/cypress/fixtures/cityChallengeResponse.json, test/cypress/fixtures/companyAddress.json
Add component FormAddSubsidiary for displaying subsidiary (address) form fields in `FormAddCompany` and `FormFieldCompanyAddress` components.
Update empty `v-model` data type (`"cityChallenge": number`) in the relevant components.
Add `cityChallenge` options fixture and update tests accordingly.
=> src/components: add  FormAddSubsidiary component for displaying subsidiary (address) form fields

src/components/__tests__/FormFieldSliderNumber.cy.js, src/components/__tests__/RegisterChallengePayment.cy.js, src/components/form/FormFieldDonation.vue, src/components/form/FormFieldSliderNumber.vue, src/components/form/FormFieldVoucher.vue, src/components/homepage/CardFollow.vue, src/components/register/RegisterChallengePayment.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue, src/router/index.ts
Show `RegisterChallengePayment` component on the register challenge page.
Update order of the inputs in the voucher section of the form based on [WF](https://www.figma.com/design/L8dVREySVXxh3X12TcFDdR/Do-pr%C3%A1ce-na-kole?node-id=4858-103791&t=C3qa44qIE3lwc0UC-1) showing first the voucher input and then the amount selection (if applicable).
Update behaviour of the voucher section in the following scenario:
- voucher "HALF" is added
- amount "Custom" is selected
- range slider input shows
- voucher "HALF" is removed
In this case, range slider input should be hidden and default amount option reset to 390.
Ensure this by updating the show condition for range input slider.
Add tests for this behaviour.
=> src/components: use RegisterChallengePayment on registration page and fix voucher section behaviour

ride_to_work_by_bike_config.toml, src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormFieldOptionGroup.vue, src/components/form/FormSelectOrganization.vue, src/components/types/Config.ts, src/composables/useApiGetSubsidiaries.ts, src/composables/useSelectedOrganization.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetSubsidiariesResponse.json, test/cypress/fixtures/apiGetSubsidiariesResponseNext.json, test/cypress/support/commands.js
Add ability to load subsidiaries based on organizationId via `useApiGetSubsidiaries` composable.
* Add API fetch behaviour in `useApiGetSubsidiaries`.
* Add fixtures and Cypress commands for testing.
* Update `FormFieldCompanyAddress.cy.js` component test to check for intercepted API methods.
* Update component `FormFieldCompanyAddress` - we no longer accept options. Instead, options are loaded based on accessing the `organizationId` field from `registerChallenge` store.
* Use correct values in `FormFieldOptionGroup` (OrganizationType enum)
* Simplify composable`useSelectedOrganization` - we can use `subsidiaryId` (computed from store) instead of `selectedAddress`
=> src/composables: add ability to load subsidiaries based on org ID via useApiGetSubsidiaries composable

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormFieldSelectTable.vue, src/components/types/Form.ts, src/composables/useSelectTable.ts
Update `FormFieldSelectTable` labels using the `useSelectTable` composable:
* Update `useSelectTable` composable to use the same structure as `useOrganizations`.
* Use composable in `FormFieldSelectTable` component.
* Update tests
--- 
In another PR, update dynamically the step 4 title based on organization type.
=> src/components: update FormFieldSelectTable labels via useSelectTable composable

ride_to_work_by_bike_config.toml, src/components/enums/Api.ts, src/components/types/Config.ts, src/composables/useApi.ts
Provide feed variant for baseUrl in useApi composable.
Allows to specify `feed` variant to call RTWBB WordPress API.
Defaults to `rest` variant for backwards compatibility.
=> src/composables: provide feed variant for baseUrl in useApi composable

src/components/__tests__/FormFieldOptionGroup.cy.js, src/components/form/FormFieldOptionGroup.vue
Fix incorrect label key in `FormFieldOptionGroup` component.
Test translation strings for `FormFieldOptionGroup` in component tests.
=> src/components: fix incorrect label in FormFieldOptionGroup component

src/components/__tests__/FormAddCompany.cy.js, src/components/__tests__/FormAddSubsidiary.cy.js, src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormAddSubsidiary.vue, src/components/form/FormFieldSelectCity.vue, src/composables/useApiGetCities.ts, src/router/index.ts
Enable loading city options from API in `FormAddSubsidiary` component.
* Use existing composable `useApiGetCities.ts`.
* Add test commands (intercept, waitForApi and model comparison) to `FormAddSubsidiary.cy.js`.
* Add API intercepts to wrapping component `FormFieldCompanyAddress.cy.js` test to prevent error messages and setup for tests when adding a new subsidiary.
* Refactor code that computes `options` array from city API results (from `FormFieldSelectCity.vue`) - expose computed property from `useApiGetCities.ts` composable, so that `options` can be used directly in the component.
=> src/components: enable loading city options from API in FormAddSubsidiary

src/components/__tests__/RegisterChallengePayment.cy.js, src/components/register/RegisterChallengePayment.vue
Fix bug where UI was showing payment options when on `company` or `school` payment.
Adds condition for `selectedPaymentSubject` value (after handling scenarios with valid discount vouchers) which clears the payment options array.
Add tests that confirm that options are hidden.
Additionally, fix a few TypeScript warnings and typos.
=> src/components: fix payment options display in RegisterChallengePayment

test/cypress/e2e/register_challenge.spec.cy.js
Issue:
Test fails when checking for "step 5" - this cannot be accessed because of validation error on Address select field.
Solution:
Extend test to check for visibility of items before selecting an option.
=> test/cypress: update register_challenge E2E test to avoid failing on dropdown select

src/components/__tests__/RegisterChallengePayment.cy.js, src/components/form/FormFieldRadioRequired.vue, src/components/register/RegisterChallengePayment.vue, src/components/types/Organization.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/utils/index.ts
Update `organizationType` prop in `registerChallenge` store after subject selection in `RegisterChallengePayment`.
* Define new enum value `none` to be able to reset `organizationType` value.
* Refactor `getRadioOption` function to share it between E2E and component tests.
* Add tests.
---
Related changes in upcoming PRs:
- Save paymentSubject to store
- Limit `organization` and `organizationType` options if `paymentSubject` is `company` or `school`
=> src/components: update organizationType in store after subject selection in RegisterChallengePayment

src/components/types/ApiTeam.ts, src/composables/useApiPostTeam.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/apiPostTeamRequest.json, test/cypress/fixtures/apiPostTeamResponse.json, test/cypress/support/commands.js
Add create a team API request with `useApiPostTeam` composable.
- Created `useApiPostTeam` composable for team creation
- Added API types in `ApiTeam.ts`
- Added test fixtures and Cypress commands for API testing
- Payload structure: `{ name: string }`
- Response structure: `{ id: number, name: string }`
=> src/composables: add useApiPostTeam() func to create/post the new team

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/__tests__/FormSelectTeam.cy.js, src/components/form/FormFieldSelectTable.vue, src/components/form/FormSelectTeam.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/support/commands.js
Use API request composable for creating a team in `FormSelectTeam` component.
* Add `useApiPostTeam` composable to create a team.
* Add a `create:option` event to notify parent component about the data update.
* Get `subsidiaryId` from `registerChallenge` store.
* Connect `team` property to `registerChallenge` store.
* Add a reload on option change.
* Refactor teams GET API intercept command to support custom response data.
* Add test for `create:option` event emission in `FormFieldSelectTable`.
* Add test for data reload after team creation in `FormSelectTeam`
* Add E2E test for team creation with updated fixture data.
=> src/components: use API request composable for creating a team in FormSelectTeam component

src/adapters/subsidiaryAdapter.ts, src/components/types/ApiSubsidiary.ts, src/composables/useApiPostSubsidiary.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/apiPostSubsidiaryRequest.json, test/cypress/fixtures/apiPostSubsidiaryResponse.json, test/cypress/support/commands.js
Add composable useApiPostSubsidiary for sending create subsidiary request
* Add composable
* Add translation string
* Add test commands
⚠️ Composable contains code to parse local form state object (type `FormCompanyAddressFields`) to payload structure required by API. Same in reverse is done on the output of the function.
TODO: Confirm that parsing is a correct approach.
=> src/composables: add composable useApiPostSubsidiary for sending create subsidiary request

src/components/global/FormFieldCompany.vue, src/components/types/apiOrganization.ts, src/composables/useApiPostOrganization.ts
Refactor API call for creating organization in FormFieldCompany to a separate composable. This is so that it can be reused on register challenge page.
Additionally, call `loadOrganizations` function inside the `onMounted` hook instead of directly in the `setup` method.
=> src/components: refactor API call for creating organization in FormFieldCompany to a separate composable

src/components/__tests__/RegisterChallengePayment.cy.js, src/components/register/RegisterChallengePayment.vue
Update default price behaviour in `RegisterChallengePayment` based on available options.
When switching between payment subjects, available payment options may change (voucher discounts first available option). For better user experience and consistent data, update `selectedPaymentAmount` based on available options.
- If current `selectedPaymentAmount` value is available in new options, select that option
- If current is not available, and default option (from config) is available select that option (most likely the first)
- If neither of the above are available, select first available option.
=> src/components: update default price behaviour in RegisterChallengePayment

src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js
Add default value for Organization step title in `RegisterChallengePage` when `organizationType` is not yet selected.
Add E2E test that checks for presence of all step titles.
=> src/pages: add default value for Organization step title in RegisterChallengePage

src/adapters/subsidiaryAdapter.ts, src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormFieldSelectTable.vue, src/components/form/FormSelectOrganization.vue, src/components/types/Form.ts, src/components/types/Organization.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiPostSubsidiaryRequest.json, test/cypress/fixtures/apiPostSubsidiaryResponse.json
Add ability to create subsidiary in `FormFieldCompanyAddress` component.
* Add composable `useApiPostSubsidiary` and use the `createSubsidiary` method.
* Update API data adapter to pass the created subsidiary `id` value to the output object.
* Rename inner variable `address` to `subsidiaryId`.
* Update logic for loading subsidiaries (without clearing `subsidiaryId` value on load).
* Add E2E and component tests.
* Update fixture to match selected challenge city ID.
=> src/components: add ability to create subsidiary in FormFieldCompanyAddress

src/components/form/FormFieldOptionGroup.vue, test/cypress/e2e/register_challenge.spec.cy.js
Limit participation options in `FormFieldOptionGroup` based on saved `paymentSubject`.
When `paymentSubject` is `school` or `company`, enable only the appropriate method of participation. Disable the rest.
Added E2E test for all `paymentSubject` variants.
=> src/components: limit participation options in FormFieldOptionGroup based on saved paymentSubject

src/components/__tests__/FormFieldSelectTable.cy.js, src/components/form/FormFieldListMerch.vue, src/components/form/FormSelectOrganization.vue, src/components/form/FormSelectTeam.vue, src/components/types/Organization.ts, src/composables/useApiGetTeams.ts, src/stores/registerChallenge.ts
For `teams`, `organizations` and `merchandise` - refactor code to load data into `registerChallenge` store instead of individual components.
This will allow to access the options values from any component (e.g. the summary).
In `FormListMerch` connect the `selectedSize` variable with store value for `merchId`.
=> src/stores: load registration options data to registerChallenge store

src/components/debug/ShowOrganizationIds.vue, src/components/form/FormFieldOptionGroup.vue, src/components/form/FormSelectOrganization.vue, src/components/form/FormSelectTeam.vue, src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/formOrganizationOptions.json
Add logic for correctly resetting organization, subsidiary, and team IDs:
* When `organizationType` changes reset `organizationId`, `subsidiaryId`, `teamId` (`FormFieldOptionGroup`).
* When `organizationId` changes reset `subsidiaryId`, `teamId` (`FormSelectOrganization`).
* When `subsidiaryId` changes reset `teamId` (`FormSelectOrganization`).
Additional changes:
* Rename variable `inputValue` to `organizationType`.
* Remove unnecessary v-model attribute on `<form-field-option-group>` component (`RegisterChallengePage`).
* Add debug component to show currently selected IDs in E2E tests.
=> src/components: add logic for resetting organization, subsidiary, and team IDs

src/components/form/FormFieldListMerch.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetMerchandiseResponseNone.json, test/cypress/support/commands.js
Issue: `FormFieldListMerch` should not allow passing to next step if `merchId` is empty (disabled button). But when checkbox "no merch" is checked and unchecked again, the `merchId` stays - makes next-step button enabled.
Solution: Fix resetting value after checkbox is unchecked.
Add test for correct working of the disabled button.
=> src/components: fix FormFieldListMerch validation by correctly clearing value after no-merch uncheck

src/components/form/FormFieldListMerch.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeNoMerch.json, test/cypress/support/commands.js
Add logic to show "I don't want merchandise" option in `FormFieldListMerch` as selected if loaded from API.
- In component, load merch-none ID for comparison (saving to an existing variable `iDontWantMerchandiseCachedId`).
- In tests, rework check for individual steps (after loading data from register-challenge GET endpoint) to allow for modification in testing the Merch step.
- Add test for fixture with selected merch-none ID `118`.
=> src/components: add logic to show selected no-merch option in FormFieldListMerch if loaded from API

src/pages/RegisterChallengePage.vue, src/router/index.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register.spec.cy.js, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/e2e/router_rules.cy.js, test/cypress/fixtures/apiGetRegisterChallengeIndividualPaidComplete.json, test/cypress/support/commands.js
Add router rule to disable `/register-challenge` route once registration is complete.
* Add getter to `registerChallenge` store.
* Add check if registration complete onMounted in `RegisterChallengePage`.
* Extend router rules with new condition.
* Test redirections in `router_rules` E2E test.
* Update `register_challenge` individual-paid test to work with incomplete data (otherwise it would be redirected).
=> src/router: add rule to disable register-challenge route once registration is complete

src/boot/pinia.js, src/composables/useApiGetCampaign.ts, src/composables/useApiGetCities.ts, src/composables/useApiGetDiscountCoupon.ts, src/composables/useApiGetFilteredMerchandise.ts, src/composables/useApiGetHasOrganizationAdmin.ts, src/composables/useApiGetMerchandise.ts, src/composables/useApiGetOrganizations.ts, src/composables/useApiGetRegisterChallenge.ts, src/composables/useApiGetSubsidiaries.ts, src/composables/useApiGetTeams.ts, src/composables/useApiPostOrganization.ts, src/composables/useApiPostPayuCreateOrder.ts, src/composables/useApiPostRegisterChallenge.ts, src/composables/useApiPostSubsidiary.ts, src/composables/useApiPostTeam.ts, src/stores/login.ts, src/stores/register.ts, test/cypress/e2e/login.spec.cy.js
Fix refreshing access token if token doesn't exists , before every REST API call.
Fix issue when PayU successful payment redirection to RTWBB URL register-challenge/ was successful (page reload), but access token is not available, and REST API register-challenge/ URL endpoint be called.
=> src/composables: fix refreshing access token, if token is not available before every REST API call

src/adapters/registerChallengeAdapter.ts, src/components/__tests__/FormFieldListMerch.cy.js, src/components/form/FormFieldListMerch.vue, src/components/types/ApiRegistration.ts, src/components/types/RegisterChallenge.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeCompanyWaiting.json, test/cypress/fixtures/apiPostRegisterChallengeMerchandiseRequest.json, test/cypress/support/commands.js, test/cypress/support/commonTests.ts
Connect fields `telephone` and `telephoneOptIn` to `registerChallenge` store and API request.
* Update UI fields in `FormFieldListMerch` (remove delivery notification checkbox + make `telephone` field always required)
* Connect fields `telephone` and `telephoneOptIn` dynamically to `registerChallenge`.
* Send new values to API via `registerChallengeAdapter`
* Update component and E2E tests to check a) saving values to store b) sending correct values in post register-challenge request c) loading correct values to UI from get register-challenge request.
=> src/stores: connect fields telephone and telephoneOptIn to registerChallenge store and API request

src/components/form/FormFieldSelectTable.vue
Scroll to initially selected item after loading options in `FormFieldSelectTable`
* Add scroll event bound to `loading` prop value change
Note: In Cypress component, the function does not trigger. It is tested manually in the app. In E2E and component tests, calling the function is registered with correct index, but UI does not update.
=> src/components: scroll to initially selected item after loading options in FormFieldSelectTable

src/components/__tests__/FormFieldPhone.cy.js, src/composables/useValidation.ts, test/cypress/e2e/register_challenge.spec.cy.js
Update phone validation regex in `useValidation` composable to be less strict and allow for international phone numbers.
* Change regex
* Update tests - relax requirements for delimiters between numbers + add examples of international numbers
=> src/composables: update phone validation regex in useValidation to be less strict

src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiPostRegisterChallengeVoucherFullRequest.json
Submit voucher data to register-challenge endpoint before creating a PayU order.
This happens in
- `100%` discount voucher + donation
- `< 100%` discount voucher (min or custom amount)
Add test for intercepting the register-challenge `post` request before PayU create order request.
=> src/pages: submit voucher data to register-challenge endpoint before creating a PayU order 

test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/formOrganizationOptions.json
Issue: `register_challenge` E2E test often fails on test:
```
1) Register Challenge page
desktop
reset organization, subsidiary and team on parent data change:
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-cy=form-select-table-team]`, but never found it.
```
Description: Organization is switched back and forth to reload subsidiaries, but, these do not update fast enough to display correct values in select (debugged in video output).
Solution:
1) Setup intercept for organization no. 2 in the list so we do not have to switch organization twice.
2) Add `waitForSubsidiariesApi` command to ensure loading data before the UI action is carried out.
=> test/cypress/e2e: update register_challenge test for resetting IDs on parent data change

src/components/__tests__/FormFieldCompanyAddress.cy.js, src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormSelectOrganization.vue, src/components/global/FormFieldCompany.vue, src/composables/useSelectSearch.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetSubsidiariesResponse.json, test/cypress/support/commands.js
Add autocomplete functionality to `FormFieldCompanyAddress` component
* Create a `useSelectSearch` composable for common filtering method
* Use the new composable in `FormFieldCompany` and `FormFieldCompanyAddress`
* Update tests to handle `FormFieldCompanyAddress` menu open click.
* Update `FormSelectOrganization` team ID reset functionality to be triggered on model update, and check original value.
* Update `apiGetSubsidiariesResponse` to get rid of a confusing duplicate entry.
=> src/components: add autocomplete functionality to FormFieldCompanyAddress

src/adapters/subsidiaryAdapter.ts, src/components/types/ApiSubsidiary.ts, src/composables/useApiGetSubsidiaries.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/support/commands.js
Add adapter for GET subsidiary data to correctly display full address.
Issue: When subsidiaries are loaded. Address is not displayed in full because of incorrect data structure
Solution: Add subsidiary get adapter to transcribe data from API into correct local data structure.
* Test that all subsidiary details are displayed.
=> src/adapters: add adapter for GET subsidiary data to correctly display full address

src/adapters/registerChallengeAdapter.ts, src/components/types/ApiRegistration.ts, src/stores/registerChallenge.ts, test/cypress/fixtures/apiPostRegisterChallengeTeamCompanyPaymentRequest.json
Add `payment_category` and `products` fields to API POST request for organization payment.
* Add fields to adapter.
* Add fields to types.
* Add fields to data posted on Team step.
* Add fields to test fixture.
=> src/stores: add payment_category and products to API POST request for organization payment

test/cypress/e2e/register_challenge.spec.cy.js
Add `waitForSubsidiariesApi` command before accessing address select values to avoid test failure caused by unavailable results.
=> test/cypress/e2e: wait for subsidiaries before accessing select values to avoid no results failure

src/composables/useStepperValidation.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js
Contributes to fixing [Bug 53](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=53)
Validate register challenge `submitStep` responses before allowing to continue to next step of registration.
Add tests for "BadRequest" status code responses at different points of registration.
=> src/composables: validate register challenge submitStep responses before allowing to continue

src/stores/login.ts, src/stores/registerChallenge.ts, src/utils/get_register_challenge_empty_state.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/e2e/register_challenge_storage.spec.cy.js, test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json, test/cypress/support/commands.js
Contributes to fixing [Bug 21](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=21)
Clear `registerChallenge` persistent store properties after logout.
* Specify which properties should be persistent in `registerChallenge` by updating the `omit` array.
* Remove outdated and unused properties `payment` and `ipAddressData`.
* Define a new util function returning empty state for persistent properties.
* Use the empty state to reset `registerChallenge` store after logging out.
* Add a `register_challenge_storage.spec` file with test for the storage function.
* Refactor `passToStepX` functions from `register_challenge.spec` file, into Cypress commands so they can be shared.
=> src/stores: clear registerChallenge persistent store properties after logout

src/components/__tests__/RegisterChallengePaymentMessages.cy.js, src/components/register/RegisterChallengePaymentMessages.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js
Fixes [Bug 16](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=16)
Add notification messages for registration step summary.
* Add message when "waiting for coordinator confirmation and organization has coordinator"
* Add message when "waiting for coordinator confirmation and organization does not have coordinator"
* Add prop to messages component and test different contexts
* Test messages in E2E tests.
=> src/components: add notification messages for registration step summary

src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormFieldSelectTable.vue, src/components/form/FormSelectOrganization.vue, src/components/register/RegisterChallengePayment.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/support/commands.js, test/cypress/support/commonTests.ts
Issue:
When option "My company pays for me" is selected, step 4 "Company" still allows to choose different company to ride for.
Steps to reproduce:
- Login to app.
- Go to `register-challenge`.
- Fill in personal details and go to next step.
- Select "My company pays for me" and select organization.
- Go to step 3 and click continue.
- Step 4 shows organizations -> you can now select any organization (this does not update organization in step 2 select).
Solution:
- If `payment_subject = company / school`, disable all organization options apart from the selected one (similar to step 3).
- If `payment_subject = company / school`, disable add new organization button.
- Ensure clearing values `subsidiaryId` and `teamId` when organization is changed in step 2 "Payment".
- Ensure clearing …
=> src/components: disable other company options than the selected when payment subject is company

test/cypress/e2e/register_coordinator.spec.cy.js
PR #871 test fails on `register_coordinator` e2e test:
`"fills in the form, submits it, and redirects to homepage on success"`
Add missing API request intercept for `isUserOrganizationAdmin` after login and wait for response.
=> test/cypress/e2e: fix issue in register_coordinator e2e test missing an intercept

src/components/__tests__/FormSelectOrganization.cy.js
Fix `FormSelectOrganization` component 'allows to create a new organization and subsidiary' test.
=> src/components/__tests__: fix checking subsidiary form field street address

cypress.config.js, src/components/__tests__/RegisterChallengePayment.cy.js, src/components/register/RegisterChallengePayment.vue, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
Fixes [Bug 5](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=5).
Issue: `checkOrganizationHasCoordinator` is being called on every `organizationId` change in `registerChallenge` store. This results in unnecessary requests.
Solution: Call `checkOrganizationHasCoordinator` from `RegisterChallengePayment` (when `organizationId` changes)
This ensures correct loading of the data when necessary.
Data is used in Payment step and also in **notification banners** on step 7 "Summary" - we always pass "Payment" to get there, therefore the state will be always available.
* Includes update of test fixture which relates to Voucher registration, and therefore does not need coordinator info.
=> src/stores: update call point for checkOrganizationHasCoordinator func to remove unnecessary API request

ride_to_work_by_bike_config.toml, src/boot/global_vars.ts, src/components/__tests__/FormFieldEmail.cy.js, src/components/__tests__/FormLogin.cy.js, src/components/__tests__/FormRegister.cy.js, src/components/__tests__/ResetPassword.cy.js, src/components/global/FormFieldEmail.vue, src/components/global/FormFieldTestWrapper.vue, src/components/login/FormLogin.vue, src/components/register/FormRegister.vue, src/components/register/ResetPassword.vue, src/components/types/Config.ts, src/css/form.scss, src/css/quasar.variables.scss, src/pages/LoginPage.vue, src/pages/RegisterPage.vue, src/pages/ResetPasswordPage.vue, src/utils/index.ts, test/cypress/e2e/login.spec.cy.js, test/cypress/e2e/register.spec.cy.js, test/cypress/e2e/reset_password.spec.cy.js, test/cypress/support/commands.js
On the registration, login, forgotten and reset password URI page. Custom color is define in app global config as `colorCustomFormFieldValidationErr` var.
=> src/component: override form fields validation error color with custom color

src/stores/registerChallenge.ts
Fixes issue where changing `payment_subject` from `company` to voucher and applying voucher 100% discount does not allow to complete registration.
Steps to reproduce:
- Login to app and start registration to challenge.
- Fill in personal details and go to step 2 "Payment".
- Select organization and continue to step 3 "Participation".
- Continue to select organization, subsidiary and team.
- Return back to step 2 "Payment".
- Select payment_subject `voucher`.
- Apply voucher 100% discount and continue.
- Complete registration to step 7 "Summary".
- User cannot complete registration.
Solution:
- Update getter `getIsPaymentComplete` (lines 244-268) to pass if 100% discount voucher is applied
- Update reading data from API on GET `/register-challenge` to only initiate 100% discount voucher in …
=> src/stores: update processing voucher on load and registration-complete condition

src/components/form/FormFieldCompanyAddress.vue, src/components/form/FormFieldSelectTable.vue, src/components/form/FormFieldVoucher.vue, src/components/global/FormFieldCompany.vue, src/components/register/FormRegisterCoordinator.vue, test/cypress/e2e/register_challenge.spec.cy.js
Add ability to submit forms by pressing enter.
* Add `@submit.prevent` handler to forms.
* Where needed add hidden submit button to forms as form submission is "[tethered to submit button](https://quasar.dev/vue-components/form#qform-api)".
* Add `q-form` element to voucher section of step 2 "Payment" to enable local submit.
* Add E2E test for the submit-with-enter behaviour.
* Fix `FormFieldSelectTable` component test (related to adding input mask in earlier commit).
=> src/components: add ability to submit forms by pressing enter

src/components/__tests__/FormRegister.cy.js, src/router/index.ts, test/cypress/e2e/challenge_inactive.spec.cy.js, test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/register.spec.cy.js, test/cypress/e2e/router_rules.cy.js, test/cypress/support/commonTests.ts
Make routing use the registration phase interval instead of challenge phase interval.
* Use correct interval `registration` for allowing users to register instaed of going to `challenge-inactive` page.
* Update test variable.
=> src/router: make routing use the registration phase interval instead of challenge phase interval

src/adapters/registerChallengeAdapter.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsChallengeNewsletter.json, test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsNoNewsletter.json
Fixes [Bug 76](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=76).
Issue: The `newsletter` value was not being saved when unselecting all options because empty fields are discarded by default.
Solution: Allow sending empty `newsletter` field so that user can clear the value by unchecking all options.
=> src/adapters: allow to submit empty newsletter field to register challenge POST API

src/adapters/registerChallengeAdapter.ts, src/components/types/ApiRegistration.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiPostRegisterChallengeVoucherNoneRequest.json
Clear voucher (both from local state and via API request) if `payment_subject` is not `voucher`.
This results in more accurate model of registration state.
=> src/stores: clear voucher on step change if payment subject is not voucher

src/components/__tests__/RegisterChallengePayment.cy.js, src/components/register/RegisterChallengePayment.vue
Fixes [Bug 74](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=74).
Make privacy policy link in `RegisterChallengePayment` coordinator form clickable.
Use `@click.stop` to stop propagation of the event to the checkbox label.
Add test which confirms the behaviour.
=> src/components: make privacy policy link in RegisterChallengePayment coordinator form clickable

src/adapters/registerChallengeAdapter.ts, src/components/__tests__/LanguageSwitcher.cy.js, src/components/global/LanguageSwitcher.vue, test/cypress/fixtures/apiGetRegisterChallengeProfileLanguageEn.json, test/cypress/fixtures/apiGetRegisterChallengeProfileLanguageSk.json, test/cypress/fixtures/apiPostRegisterChallengeLanguageEn.json, test/cypress/fixtures/apiPostRegisterChallengeLanguageSk.json
Issue: Currently, language is saved only on registration (step personal details), but UI does not allow to update it later (when selecting from language-switcher).
Solution: Add register-challenge PUT method to the `LanguageSwitcher` component.
---
Blocked by: Backend currently returns message "sk" is not a valid language option.
=> src/components: save language on selection in LanguageSwitcher component

src/components/form/FormFieldVoucher.vue, test/cypress/support/commands.js
Before send it to the REST API validation, to prevent get unexpected error message.
Fixes following [bug](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=78).
=> src/components/form: fix removing space from the typed discount coupon string

src/components/__tests__/CountdownEvent.cy.js, src/components/homepage/CountdownEvent.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/e2e/home.spec.cy.js
Fixes [Bug 83](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=83).
Update `CountdownEvent` component title to correctly show challenge month.
* Update translation key to depend on `challengeMonth` config var.
* Add translation strings for different options.
Additional change: Fix `home.spec` E2E test by updating the number of expected items in bottom panel.
=> src/components: update CountdownEvent component title to correctly show challenge month

src/adapters/payuAdapter.ts, src/components/register/RegisterChallengePayment.vue, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetDiscountCouponResponse95.json, test/cypress/fixtures/apiGetThisCampaignMay.json, test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucher95NoDonation.json, test/cypress/support/commands.js, test/cypress/support/commonTests.ts
Fixes [Bug 85](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=85).
Issue: When discount amount is calculated as a decimal number (to be rounded up, e.g `23.5Kč`), some parts of code do not correctly calculate rounded amount (`24Kč`). This results in incorrect `if` statement result in `payuAdapter.ts:76`, and that in turn prevents user to send payment order.
Solution: Add missing rounding functions in `payuAdapter.ts` and `RegisterChallengePayment.vue`.
Add E2E test which tests specific case with decimal voucher discount. Add new fixtures and timestamp for this test.
=> src/adapters: add missing rounding function for coupon discount calculation

src/components/register/RegisterChallengePayment.vue, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeVoucher95NotApplied.json
Fixes [Bug 86](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=86).
Load coupon on register challenge refresh in `registerChallenge` store.
Issue: When registration is loaded the logic incorrectly assumes 100% discount from saved coupon.
Solution:
* Recheck voucher via API on load.
* Add `{ immediate: true }` to `RegisterChallengePayment` watchers to display voucher data in Payment step on load.
* Add E2E test with a new fixture for given case.
=> src/stores: load coupon on register challenge refresh in registerChallenge store

test/cypress/e2e/company_coordinator.spec.cy.js
Fix Cypress company_coordinator e2e 'displays company coordinator disabled text' test.
Error message:
```
1) Company Coordinator Page
general
displays company coordinator disabled text:
AssertionError: Timed out retrying after 60000ms: expected 'https://dpnk.dopracenakole.net/' to equal undefined
```
=> test/cypress/e2e: fix Cypress company_coordinator e2e 'displays company coordinator disabled text' test

src/components/__tests__/NewsletterItem.cy.js, src/components/homepage/NewsletterFeature.vue, src/components/types/Newsletter.ts, src/mocks/homepage.ts, test/cypress/e2e/home.spec.cy.js
Issue: When switching between languages on homepage, labels for different newsletter subscriptions do not change and only show in Czech language.
Solution: Change the newsletter items list to `computed` value to update on language change.
* Update the `NewsletterItem` type, which should no longer contain the `following` property.
* Simplify the `newsletterItems` import in `NewsletterFeature` component.
* Update `NewsletterItem.cy.js` component test to use the `.value` of the computed ref.
* Add E2E test which validates correct language of labels when given locale is selected.
=> src/mocks: update newsletter items list to computed value to show dynamically translated labels

src/components/__tests__/FormUpdatePhone.cy.js, src/components/__tests__/ProfileDetails.cy.js, src/components/form/FormUpdatePhone.vue, src/components/profile/ProfileDetails.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/e2e/profile.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedTelephone.json
Allow updating user phone in `ProfileDetails` component.
* Add `FormUpdatePhone` component for the form UI inside modal.
* Use the new form component to allow updating phone number.
* Add fixture for testing updated phone number.
* Add component tests for `FormUpdatePhone` and `ProfileDetails` components
* Add E2E test in `profile.spec` file.
Additional change: Update E2E test name in `profile.spec.cy.js:107` to correctly list tested values updates.
=> src/components: allow updating user phone number in ProfileDetails component

src/components/__tests__/FormFieldEmail.cy.js, src/components/global/FormFieldEmail.vue, src/composables/useValidation.ts
Add `required` prop to `FormFieldEmail` component.
This will be used in Profile page edit form.
* Add `required` prop and use it in validation
* Update validation for email to pass if value is empty
* Update component tests, removing the unnecessary wrapper component and adding test for optional variant.
* Update `isEmailList` validation condition to keep requiring values.
=> src/components: add required prop to FormFieldEmail component

src/components/__tests__/FormFieldEmail.cy.js, src/composables/useValidation.ts
Fixes [Bug 98](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=98).
* Allow uppercase letters for email input in `useValidation` composable.
* Add test for validating emails with uppercase letters.
Backend functionality tested by logging in with active account details in uppercase form.
=> src/composables: fix email form field validation letter case insensitive rule

public/icons/drawer_menu/icons.svg, ride_to_work_by_bike_config.toml, src/adapters/registerChallengeAdapter.ts, src/components/__tests__/DrawerMenu.cy.js, src/components/global/MobileBottomPanel.vue, src/components/types/ApiRegistration.ts, src/components/types/Config.ts, src/components/types/RegisterChallenge.ts, src/composables/useMenu.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/layouts/MainLayout.vue, src/stores/registerChallenge.ts, src/utils/get_register_challenge_empty_state.ts, test/cypress/e2e/home.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeIndividualPaidCompleteStaff.json, test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json, test/cypress/support/commands.js, test/cypress/support/commonTests.ts
Fixes [Bug 103](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=103).
Add staff menu link to app administration in `useMenu` composable.
* Use localized link to app admin (from global config).
* Update component test for `DrawerMenu` where composable is being used.
* Add more robust test for `MobileBottomPanel` where composable is being used.
* Add and update necessary fixtures.
=> src/composables: add Django admin menu link item into home page menu

src/adapters/couponAdapter.ts, src/components/form/FormFieldVoucher.vue, src/components/types/Coupon.ts, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetDiscountCouponResponseOneTime.json, test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
Fixes [Bug 101](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=101).
Issue: One-time (single use) coupons can be used but any subsequent load shows error message. This is because adapter considers availability as equal to validity.
Solution: 
* Add a property `available` to the property `valid` to `ValidatedCoupon` object.
* Add the availability constraint to coupon application (but not to loading coupon info).
* Add test for loading already applied one-time coupon (the coupon should be shown in the Payment step).
=> src/adapters: update loaded properties of discount coupon to correctly load one-time coupons

src/components/register/RegisterChallengePaymentMessages.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/RegisterChallengePage.vue, src/stores/registerChallenge.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetRegisterChallengeIndividualWaitingMinAmount.json
Add loader waiting period after user cancels PayU payment to prevent accidentally overwriting registration state.
* Add state variable `isPeriodicCheckInProgress` to `registerChallenge` store.
* Use the new variable to display `q-inner-loading` component in `RegisterChallengePage`
* Add loader label.
* Use `getIsPaymentSuccessful` to check payment success to accept both `done` and `no_admission` (motivated by failing tests).
* Make `isWaitingForConfirmation` message in `RegisterChallengePaymentMessages` show only for subject organization (motivated by current use case).
=> src/stores: add loader waiting period after user cancels PayU payment

test/cypress/e2e/register_challenge.spec.cy.js
Issue: Some of the `register_challenge.spec.cy.js` E2E tests fail because they are comparing current prices with prices fixed in given time.
Solution: Use `clock` to specify fixed time for test.
Additionally, resolve another problem, where tests stopped working after redirecting to PayU. Use response fixture with empty redirect field to stop test from redirecting to new URL before test finishes.
=> test/cypress/e2e: use clock for fixed time in register challenge voucher tests

src/pages/RegisterChallengePage.vue, test/cypress/e2e/register_challenge.spec.cy.js
Update visibility for the Complete Registration button on register challenge summary step.
* Where before, we had disabled button "Complete registration", (waiting for payment confirmation), now button is not visible at all.
* Update E2E tests for given scenarios, and add E2E test for successful registration completion in the "individual payment" user route.
=> src/pages: fix complete registration button visibility

src/components/__tests__/FormRegisterCoordinator.cy.js
Issue: Currently `FormRegisterCoordinator` component test fails with message:
```
1) <FormRegisterCoordinator>
mobile
validates checkboxes correctly:
AssertionError: Timed out retrying after 60000ms: Expected not to find content: 'Musíte souhlasit se zpracováním osobních údajů' but continuously found it.
```
Update selectors to target clicks on checkbox instead of label element which contains external link.
=> src/components/__tests__: fix checkbox element selector

src/composables/useMenu.ts
Show prizes page in the sidebar menu and bottom mobile panel by adding it to `useMenu` composable.
---
TODO: Confirm prizes functionality
=> src/composables: add home page prizes menu link item

src/adapters/registerChallengeAdapter.ts, src/components/__tests__/FormFieldSelectCity.cy.js, src/components/form/FormFieldSelectCity.vue, src/components/types/ApiRegistration.ts, src/components/types/City.ts, src/pages/IndexPage.vue, src/pages/PrizesPage.vue, src/stores/registerChallenge.ts, test/cypress/e2e/home.spec.cy.js, test/cypress/e2e/prizes.spec.cy.js, test/cypress/fixtures/apiGetCitiesResponse.json, test/cypress/fixtures/apiGetCitiesResponseNext.json, test/cypress/fixtures/apiGetRegisterChallengeProfile.json
Add API field `wp_slug` to be used in `FormFieldSelectCity` component.
This is to allow app BE to be synced with current WP slugs independent of city names.
* Add API field `wp_slug` to `cities/` and `register-challenge/` GET endpoints.
* Update tests and components accordingly.
* Update `FormFieldSelectCity` to handle a) `wp_slug` different from `slug` b) `wp_slug` being a non-unique identifier (QSelect option `value` is `slug` field, which should be unique).
=> src/components: use REST API wp_slug field in the FormFieldSelectCity component 

src/components/__tests__/RegisterChallengePaymentMessages.cy.js, test/cypress/fixtures/apiGetDiscountCouponResponseHalfWithDonation.json
Issue:
Component test  for `RegisterChallengePaymentMessages` occasionally fails on test `renders donation success message for voucher full with donation`.
This PR adds API request intercept for the coupon code used in the register-challenge data fixture. This fixes error messages within the test and stops test from failing (on 10 consecutive runs).
=> src/components/__tests__: fix RegisterChallengePaymentMessages component tests by intercepting coupon validation request

src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RouteTabs.vue, src/components/routes/RoutesCalendar.vue, src/stores/challenge.ts, test/cypress/fixtures/routeListCalendar.json
Update calculation for enabled and disabled dates in `RoutesCalendar`.
* `RoutesCalendar.vue` - update logic for calculating the `disabled-before` and `disabled-after` attribute values based on `challenge` phase, current date and the `days_active` of campaign (logging window). 
* `RoutesCalendar.vue` - add temporary prop for testing (will be replaced by fetching routes from store).
* `RoutesCalendar.cy.js` - add tests related to enabled and disabled sections of calendar on different dates.
* `RoutesCalendar.cy.js` - reorganize (thanks to using scope for `cy.clock` function, we no longer need to separate pop-up panel test into a standalone context - moved tests to `coreTests` function).
=> src/components: update calculation for enabled and disabled dates in RoutesCalendar

ride_to_work_by_bike_config.toml, src/adapters/feedAdapter.ts, src/components/enums/Offers.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/pages/PrizesPage.vue, test/cypress/e2e/prizes.spec.cy.js, test/cypress/fixtures/apiGetOffersResponse.json, test/cypress/fixtures/apiGetOffersResponseAlternative.json
Display a list of upcoming events on `PrizesPage`.
* Extend `feedAdapter` to get events from fetched posts.
* Add enum for type distinction between `oneDayEvent` and `multiDayOffer`.
* Display Event in cards (same as offers).
* Extend E2E tests (and fixtures where needed - add event-type data).
=> src/pages: display a list of upcoming events on PrizesPage component

quasar.config.js, src/components/__tests__/RouteTabs.cy.js, src/components/routes/RouteTabs.vue, src/pages/RoutesPage.vue
Hide Map and App tabs in `RouteTabs` component.
* Enable `hidden` prop in `RouteTabs` component which allows to dynamically hide some tabs.
* Hide `map` and `app` tabs on `RoutesPage.vue`
* Update component tests.
=> src/components/routes: hide Map and App tabs in RouteTabs component

src/components/enums/Challenge.ts, src/stores/registerChallenge.ts, src/utils/price_levels.ts, test/cypress/e2e/register_challenge.spec.cy.js, test/cypress/fixtures/apiGetThisCampaign.json, test/cypress/fixtures/apiPostRegisterChallengeTeamSchoolPaymentRequest.json, test/cypress/fixtures/getCurrentPriceLevelsUtilTestData.json
Add logic for loading `school` pricing from campaign API and send it as the `payment_amount` field in `registerChallenge` store.
* Add `PriceLevelCategory` `school`.
* Update `price_levels.ts` util to process new category.
* Add logic to send new price based on paymentSubject in `registerChallenge`.
* Add E2E test and update test data in `getCurrentPriceLevelsUtilTestData` fixture (used in `unit_utils_tests.cy.js`).
=> src/stores: add logic for loading school pricing from campaign API

quasar.config.js, ride_to_work_by_bike_config.toml, src/components/__tests__/FormFieldSelectCity.cy.js, src/components/form/FormFieldSelectCity.vue, src/components/types/Config.ts, src/pages/CommunityPage.vue, src/pages/IndexPage.vue, src/pages/PrizesPage.vue, src/stores/feed.ts, src/stores/login.ts
Add new store `feed.ts` and cache data fetched from WordPress endpoint.
* Refactor loading offers, prizes and cities into `feed.ts` store.
* Add persistency and caching mechanism - loading feed once in 24 hours.
* Use the store actions to fetch data on `IndexPage` and `PrizesPage`.
* Update `FormFieldSelectCity.vue` to accept `cities` prop from wrapping page - this allows to first fetch cities and then set the initial select value, all within the page `onMounted` hook.
* Update loading cities on `CommunityPage`.
=> src/stores:  add new feed store  with caching data ability 

ride_to_work_by_bike_config.toml, src/components/types/Config.ts, src/pages/IndexPage.vue, src/pages/PrizesPage.vue, src/utils/get_feed_param_set.ts, test/cypress/support/commands.js
Add config vars for max loaded posts param in feed API query.
* Replace fixed `_number` parameter in prizes and offers request param with dynamic value from global config.
=> config: add app config global vars for max loaded posts param in feed API query URL

src/adapters/feedAdapter.ts, test/cypress/e2e/prizes.spec.cy.js, test/cypress/fixtures/apiGetOffersResponse.json
Update `tShirtEvent` field value calculation for front-end conditional `OfferValidation` display.
* API field `akce_na_triko` returns string values `"1"` or `"0"` - adjust the adapter translation of the value accordingly.
* Update tests and check results with API values `"1"` or `"0"` and `""`.
=> src/adapters: fix tShirtEvent field value calculation for displaying OfferValidation component element

src/pages/IndexPage.vue, src/pages/PrizesPage.vue, src/stores/feed.ts
Fix loading posts on `IndexPage` and `PrizesPage`
Additionally, address the following issue:
* Go to the page `/prizes`.
* Select another city than my default competition city.
* Go to `/home` or another page.
* Come back to `/prizes`.
* Component should display posts for the default competition city again (reset), but shows the saved posts for another city that was previously selected.
To prevent this, reset the `feed` store when leaving the `PrizesPage` with other than the default city selected.
=> src/pages: fix loading posts on IndexPage and PrizesPage + add reset to default city

quasar.config.js, ride_to_work_by_bike_config.toml, src/adapters/tripsAdapter.ts, src/components/__tests__/RouteCalendarPanel.cy.js, src/components/__tests__/RouteListEdit.cy.js, src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RouteCalendarPanel.vue, src/components/routes/RouteInputDistance.vue, src/components/routes/RouteItemEdit.vue, src/components/routes/RoutesCalendar.vue, src/components/types/Config.ts, src/components/types/Trip.ts, src/composables/useApi.ts, src/composables/useApiPostTrips.ts, src/composables/useCalendarRoutes.ts, src/composables/useLogRoutes.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/stores/trips.ts, src/utils/has_transport_distance.ts, src/utils/index.ts, test/cypress/e2e/routes_calendar.cy.js, test/cypress/fixtures/apiGetTripsResponseCalendar.json, test/cypress/fixtures/apiGetTripsResponseCalendarNext.json, test/cypress/fixtures/routeCalendarInputTest.json, test/cypress/fixtures/routeCalendarPanelInputTest.json, test/cypress/support/commands.js
Add ability to log routes from Calendar view with useApiPostTrips composable.
* Add `data-date="timestamp.date"` attribute to calendar dates for easier targeting in tests.
* Add convert function from `RouteItem[]` to `TripPostPayload` in `tripsAdapter`.
* Add composable function for logging routes.
* Use the new composable function in `RouteCalendarPanel.vue` to log routes with the `'input-number'` method.
* Add `trips` store action to merge saved routes from API response with currently loaded routes.
* Add `RouteCalendarPanel` component tests for different configurations of inputs.
* Add E2E test to check that routes are updated in UI after saving.
=> src/composables: add ability to log routes from Calendar view with useApiPostTrips composable

src/components/__tests__/DrawerMenu.cy.js, src/components/global/MobileBottomPanel.vue, src/composables/useMenu.ts, src/layouts/MainLayout.vue, src/router/routes.ts, test/cypress/e2e/main_menu.spec.cy.js, test/cypress/fixtures/apiGetThisCampaignMay.json, test/cypress/fixtures/mainMenuDisplayTest.json, test/cypress/fixtures/mobileMenuDisplayTest.json, test/cypress/support/commands.js, test/cypress/support/commonTests.ts
Programmatically enable Routes menu item when `competition` or `entry_enabled` phase starts.
* Add `isEntryEnabled` as a parameter for `getMenuTop` function.
* Use the parameter in `DrawerMenu` and `MobileBottomPanel`.
* Add E2E test which checks the disabled state of menu items depending on active phase.
Additionally, update the setup for `routes.ts` route redirect:
Issue: In current state, 1st click on "Routes" menu item redirects to calendar, but second click goes to the empty `/routes` page.
The `redirect` setting ensure that user is always redirected to one of the children pages.
=> src/composables: enable Routes menu item when competition or entry phase starts

quasar.config.js, src/components/__tests__/RouteCalendarPanel.cy.js, src/components/__tests__/RouteItemEdit.cy.js, src/components/__tests__/RouteListEdit.cy.js, src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/CalendarItemDisplay.vue, src/components/routes/RouteCalendarPanel.vue, src/components/routes/RouteInputTransportType.vue, src/components/routes/RouteItemEdit.vue, src/components/types/Route.ts, src/composables/useCalendarRoutes.ts, src/composables/useLogRoutes.ts, src/composables/useRoutes.ts, test/cypress/fixtures/routeCalendarEmptyFromWork.json, test/cypress/fixtures/routeCalendarEmptyToWork.json, test/cypress/fixtures/routeCalendarInputTest.json, test/cypress/fixtures/routeCalendarPanelInputTest.json, test/cypress/fixtures/routeEmptyFromWork.json, test/cypress/fixtures/routeEmptyToWork.json, test/cypress/fixtures/routeListItemEmpty.json
Set default transport type for routes in list view to null (do not use default value `no_work`).
Issue: Currently, there is no distinguishing feature between logged `no_work` route, and unlogged route.
Set default `transport` for empty routes depending on the view:
- Calendar: unlogged routes in calendar have value `null` (visually empty box with "+" sign). For active routes that are passed to `RouteCalendarPanel`, set default to `bicycle` if not already logged (for easier entry - better UX).
- List: unlogged routes in list have value `null` (no selected transport button). In display list, this is signaled by "?" icon and "Not logged" label.
Additional changes:
- Update test fixtures to match the inputs for different route related components.
- Fix TS type errors where needed.
=> src/composables: set default transport type for routes in list view to null (do not use default value)

src/adapters/feedAdapter.ts
Remove timezone key from data fields in offers.
This fixes inconsistency in back-end data and ensures the posts are displayed with correct start time.
=> src/adapters: remove timezone offset Z char from post_date field date time string value in offers 

src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RoutesCalendar.vue, test/cypress/fixtures/routeCalendarInputTest.json, test/cypress/fixtures/routeCalendarPanelInputTest.json
Make `RoutesCalendar` show entry slots only for days in challenge phase.
* Add function to check if day timestamp is within phase competition date range.
* Extend test campaign range by one day to be able to test dates outside current month.
Additional change:
* Fix TS issue with `dateMinusOneDay` and `datePlusOneDay` being `possibly null`.
=> src/components/routes: make RoutesCalendar show entry slots only for days in challenge phase

test/cypress/fixtures/usefulLinks.json, test/cypress/fixtures/usefulLinksMobileApp.json
Since RTWBB mobile app has been removed from the store, link no longer returns OK response as needed for tests.
* Remove link to mobile app from `MenuLinks` data.
Component is currently not displayed in front-end app.
=> test/cypress/fixtures: remove mobile app link from the home page panel

src/components/__tests__/RoutesCalendar.cy.js, src/components/routes/RoutesCalendar.vue, test/cypress/e2e/routes_calendar.cy.js, test/cypress/fixtures/routeCalendarPanelInputTest.json, test/cypress/support/commonTests.ts
Enable logging routes outside current month in `RoutesCalendar`.
It makes for better UX, if user is able to log all available routes which are currently in view, instead of being limited by current month.
* Enable feature in calendar
* Update some component test and test data: 1) update end of challenge date to correspond to fixture, 2) for test that should work within a single month, choose September campaign data, 3) update variable names to reflect this.
* Add E2E test for logging route outside current month.
=> src/components: enable logging routes outside current month in RoutesCalendar

quasar.config.js, src/components/__tests__/RouteCalendarPanel.cy.js, src/components/__tests__/RouteListEdit.cy.js, src/components/global/MobileBottomPanel.vue, src/components/routes/RouteCalendarPanel.vue, src/components/routes/RouteListEdit.vue, src/composables/useRoutes.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/layouts/MainLayout.vue
Add `isEntryEnabled` variable to `useRoutes` to control sending the route logging requests.
* Refactor logic to get `isEntryEnabled` variable to the `useRoutes` file.
* Use it to display notification if user tries to log routes outside the entry-enabled period.
* Add test case to `RouteCalendarPanel` and `RouteListEdit` component tests.
=> src/composables: add isEntryEnabled variable to control sending route logging request

src/components/__tests__/RouteItemEdit.cy.js, src/components/__tests__/RouteListEdit.cy.js, src/components/routes/RouteItemEdit.vue, src/components/routes/RouteListEdit.vue, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, test/cypress/fixtures/routeItemsCalendar.json
Enable automatic QForm validation on save in `RouteListEdit` for distance inputs.
* Use `v-if="isShownDistance"` in `RouteItemEdit` to fix issue with invalid hidden inputs (distance).
* Add validation and notification to `RouteListEdit` `onSave` function.
* Update test fixture not to contain empty routes and to contain empty route slot for test.
* Add component test for validation check.
=> src/components: enable list of distance input elements form validation before saving

ride_to_work_by_bike_config.toml, src/components/routes/RouteListDisplay.vue, src/composables/useRoutes.ts
Localize day names in route lists via `useRoutes` composable.
* Define `"weekday"` format for i18n plugin.
* Use `i18n.global.d` function instead of Quasar's `date.formatDate` (which needs to be [localized manually](https://quasar.dev/quasar-utils/date-utils#format-for-display)).
* Capitalize first letters with `text-capitalize` class.
=> src/composables:  fix day names, month days localization in routes lists 

src/components/routes/RouteCalendarPanel.vue, src/components/routes/RouteListDisplay.vue, src/components/routes/RouteListEdit.vue, src/components/routes/RoutesCalendar.vue, src/composables/useApiPostTrips.ts, test/cypress/e2e/routes_calendar.cy.js, test/cypress/e2e/routes_list.spec.cy.js, test/cypress/support/commands.js
Add loading spinners to route display components.
* Add spinners to `RoutesCalendar` `RouteListDisplay` and `RouteListEdit`.
* Add delay to get-trips intercept to be able to test loaders.
* Add loader checks to E2E tests.
=> src/components/routes: add loading spinners to route display components

test/cypress/e2e/routes_calendar.cy.js, test/cypress/e2e/routes_list.spec.cy.js
Issue: E2E tests fail because they contain incorrect comparison string.
Solution: Update comparison string in `routes_calendar` and `routes_list`.
=> test/cypress/e2e: fix comparison translated strings for test notification

src/components/homepage/NewsletterFeature.vue, src/pages/IndexPage.vue, src/pages/RegisterChallengePage.vue, src/stores/challenge.ts, src/stores/login.ts, test/cypress/e2e/login.spec.cy.js
Add conditions for loading registration and challenge data + clear store on logout.
* Ensure that `register-challenge` data is loaded after login, before redirecting to homepage (this should bypass going to /#/register-challenge page, to fetch data about register-challenge unless user is not registered).
* Add method `resetPersistentProperties` to challenge store to clear store on logout.
* Add E2E test checking for the sent requests.
=> src/stores: add conditions for loading registration and challenge data + clear store on logout

src/stores/login.ts, src/stores/trips.ts, test/cypress/e2e/login.spec.cy.js
Clear trips store after logout to force trips reload on new login.
* Add `clearRouteItems` function to `trips` store.
* Use `clearRouteItems` function on logout.
* Test that trips GET API request is called after logout + login (E2E).
=> src/stores: clear trips store after logout to force trips reload on new login

test/cypress/e2e/register_coordinator.spec.cy.js
Issue: `register_coordinator` test fails because it is waiting for response from `register-challenge` endpoint.
Solution: Add intercept for `register-challenge` get request.
=> test/cypress/e2e: intercept register-challenge get request in register_coordinator e2e test

test/cypress/e2e/router_rules.cy.js
Issue: E2E test `router_rules` fails because it is waiting for response from `register-challenge/` and `is-user-organization-admin/` endpoints.
Solution: Add intercepts for `register-challenge/` and `is-user-organization-admin/` endpoints.
=> test/cypress/e2e: intercept requests in router_rules e2e test

test/cypress/e2e/register_challenge.spec.cy.js
Issue: E2E tests `register_challenge` fail because it is waiting for response from `my-team/` and `is-user-organization-admin/` endpoints.
Solution: Add intercepts for `my-team/` and `is-user-organization-admin/` endpoints in section shared for all contexts.
=> test/cypress/e2e: intercept requests in register_challenge e2e tests

test/cypress/e2e/strava.spec.cy.js
Add missing intercepts to `strava.spec` test.
* `commute-mode/`, `trips/` - for accessing `#/routes` URL.
* `open-app-with-rest-token` - for accessing `#/routes/connect-third-party-apps` URL.
=> test/cypress/e2e: add missing intercepts to strava.spec test

src/components/global/FooterBar.vue, src/components/routes/RouteListEdit.vue, test/cypress/e2e/routes_list.spec.cy.js, test/cypress/support/commands.js
Fixes [Bug 123](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=123)
Update `RouteListEdit` floating button position with Vue `<teleport>`:
* Teleport the QLayout + QPageSticky wrapper to the bottom of the body to fix the stacking.
* Add conditional spacing element in `FooterBar` for the `routes-list` path to make space for floating button when scrolled to the bottom of the page.
* Add tests.
=> src/components: fix footer content covers the save routes button on mobile screen

src/components/routes/RoutesApps.vue, test/cypress/e2e/strava.spec.cy.js
Fixes [Bug 125](https://bugzilla.dopracenakole.net/bugzilla/show_bug.cgi?id=125)
Remove URL parameters after Strava account auth.
This prevents a bug where page refresh calls the `authAccount` action again with the same code which is now invalid.
=> src/components: remove URL parameters after Strava authentication

src/adapters/tripsAdapter.ts
Trips REST API URL endpoint `distanceMeters` field require integer value type.
=> src/adapters: fix trips REST API URL endpoint payload distanceMeters field int value type

src/components/__tests__/ResultsTabs.cy.js, src/components/enums/Results.ts, src/i18n/cs.toml, src/i18n/en.toml, src/i18n/sk.toml, src/stores/results.ts, test/cypress/fixtures/apiGetResultsResponses.json, test/cypress/support/commands.js
Add new tab `teamRegularityCity` to results page.
* Add key to be fetched (only if user is organization admin).
* Add labels.
Additional change: Fix `ResultsTabs.cy.js` test which sometimes awaited intercepted responses in the wrong order.
* Add unique keys to intercepts and awaits to prevent data mismatch.
=> src/stores/results: add new tab teamRegularityCity to results page

test/cypress/e2e/routes.spec.cy.js
Issue: `routes.spec.cy.js` tends to fail as it does not reliably redirects from root `routes` path to `calendar`.
Fix this by specifying explicitly the navigation to `routes_calendar` path.
=> test/cypress/e2e: fix routes test by setting exact destination path

src/components/routes/StravaApp.vue, test/cypress/e2e/strava.spec.cy.js
Issue: `strava.spec.cy.js` test fails on CI (only) awaiting request loading Strava account.
Approach: Remove some non-standard test structure and simplify the beforeEach intercept hooks (solution tested in CI).
=> test/cypress/e2e: limit cypress-specific code with timeout in StravaApp to component tests

src/stores/challenge.ts, test/cypress/e2e/router_rules.cy.js, test/cypress/fixtures/appAccessTestData.json, test/cypress/fixtures/loginTokensTestData.json, test/cypress/support/commonTests.ts
* Update checking for phase range with Quasar utils.
* Update `systemTimeRegistrationPhaseInactive` timestamp to account for timezone shift in locally run tests.
* Update generative app access tests to also check for route logging availability.
=> src/stores/challenge: update checking for phase range with Quasar utils

test/cypress/e2e/register_challenge.spec.cy.js
Issue: E2E test `register_challenge.spec.cy.js` sometimes fails with the following message:
```
CypressError: Timed out retrying after 12000ms: `cy.wait()` timed out waiting `12000ms` for the 1st request to the route: `thisCampaignRequest`. No request ever occurred.
```
Analysis:
The problem is probably caused by a race condition on these three lines:
```
150: cy.visit('#' + routesConf['challenge_inactive']['path']);
151: cy.waitForThisCampaignApi();
...
153: cy.visit('#' + routesConf['register_challenge']['path']);
```
Redirection happens faster than the request can be fired - therefore it is never registered.
Solution:
Add waiting for page (challenge-inactive) load - this ensures that API request has time to start:
```
151: cy.dataCy('challenge-inactive-info').should('be.visible');
```
=> test/cypress/e2e: add page load check to ensure API request trigger

src/adapters/tripsAdapter.ts, src/composables/useCalendarRoutes.ts, src/composables/useLogRoutes.ts, src/composables/useSelectSearch.ts, src/stores/login.ts, src/utils/get_register_challenge_empty_state.ts
This PR fixes some issues discovered by running `npx tsc --noEmit`.
1. `src/utils/get_register_challenge_empty_state.ts` - Added `email: ''` property to `emptyFormPersonalDetails`
2. `src/stores/login.ts` - Added `showErrorMessage: false` property to `defaultLoginOptions`
3. `src/composables/useCalendarRoutes.ts` - Add `file: null` property to the route object
4. `src/composables/useSelectSearch.ts` - Fix typing of `optionsFiltered`
5. `src/adapters/tripsAdapter.ts` - Add null check for `routeItem.transport` and `hasTransportDistance()`
6. `src/composables/useLogRoutes.ts` - Add null check before calling `hasTransportDistance()`
=> src/composables: fix miscellaneous Typescript errors 

test/cypress/e2e/routes_calendar.cy.js
Issue: `routes_calendar.cy.js` test sometimes fails with:
```
1) Routes calendar page
desktop - with logged routes
enter distance, upload a file, then log route by entering distance:
AssertionError: expected [ Array(1) ] to have the same members as [ Array(1) ]
[ { trip_date: '2025-05-20',
direction: 'trip_to',
commuteMode: 'bicycle',
-    distanceMeters: 100,
+    distanceMeters: 10000,
sourceApplication: 'RTWBB web app' } ]
at Context.eval (webpack://ride-to-work-by-bike/./test/cypress/support/commands.js:3676:48)
```
Solution: This is likely an issue with entering value into the masked input after switching from file input. Approach is to validate input state in UI when clearing the value and before submitting.
=> test/cypress/e2e: add Cypress command to validate input value after typing

test/cypress/e2e/register_challenge.spec.cy.js
Issue: E2E test `register_challenge.spec.cy.js` occasionally fails with message:
```
1) Register Challenge page
desktop
allows to complete registration with voucher payment FULL:
CypressError: Timed out retrying after 60050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:
> <div.q-field__append.q-field__marginal.row.no-wrap.items-center.q-anchor--skip>
We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page.
```
Cause: This is likely due to asynchronous loading of the content (.q-field__append which is being clicked contains loader when loading data and switches to dropdown arrow when ready)
Solution: Add `q-spinner` non-existence check …
=> test/cypress/e2e: add Cypress check command for async data for dropdown select before interaction

test/cypress/e2e/profile.spec.cy.js
Issue: E2E test `profile.spec.cy.js` occasionally fails with message:
```
1) Profile page
change email
"before each" hook for "allows user to change email":
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-cy=index-title]`, but never found it.
```
Cause: This is caused by a state where POST request to auth token is not valid and login (part of the before each step) is not completed. This usually isn't a problem as this test does not have route guards enabled, but it seems it can prevent redirect to homepage.
Solution: To fix this, set the internal Cypress clock time to time before the token expiration.
=> test/cypress/e2e/profile: set Cypress internal time to fix the login command in before each hook

src/components/register/ResetPassword.vue, test/cypress/support/commands.js
Issue: `reset_password.spec.cy.js` test occasionally fails with message:
```
1) Reset Password
desktop
submits form successfully and redirects to login:
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-cy=form-reset-password-input]`, but never found it.
```
This suggests a race condition: Successful API request triggers redirect. Test validates API request and then tries to check UI state (cleared inputs). If redirect happens before the UI test, Cypress will not find the required inputs.
Solution: Add an exception-wait time to the component. To allow the tests to execute.
=> test/cypress/e2e/reset_password: add delay to confirmation to have time to check UI

test/cypress/e2e/register_coordinator.spec.cy.js
Issue: register_coordinator E2E test occasionally fails with message:
```
1) Login page
desktop with API intercepts
fills in the form, submits it, and redirects to homepage on success:
CypressError: Timed out retrying after 12000ms: `cy.wait()` timed out waiting `12000ms` for the 1st request to the route: `getOrganizationsNextPage`. No request ever occurred.
```
Cause: In this scenario, test never navigates to `register_coordinator` route. Stays on HP and therefore does not load appropriate API endpoint.
Solution: Add visibility check for HP title, to make sure page loads before it navigates to `register_coordinator` route.
=> test/cypress/e2e/register_coordinator: wait for HP to load before redirect command

src/components/__tests__/NewsletterFeature.cy.js
Issue: `NewsletterFeature` component test sometimes fails with message:
```
1) loads newsletter settings from API
<NewsletterFeature>
mobile
loads newsletter settings from API:
AssertionError: expected { Object (count, next, ...) } to deeply equal { Object (count, next, ...) }
next: null,
previous: null,
results: 
[ { personal_details: [Object],
-       city_slug: 'praha',
-       city_wp_slug: 'praha',
organization_type: 'company',
```
Cause: This is likely caused by race condition between executing an API request and overriding the intercept - the GET requests still compares the old intercepted version with the fixture data expecting new intercept.
Solution: Add check for the number of requests to wait for the correct version of data to be intercepted (GET should be …
=> src/components/__tests__/NewsletterFeature: update awating API requests to ensure sequential checks
